REM PROJECT: BLACK JACK ATARI FAST BASIC. PORTED FROM DARK BASIC VERSION.
REM CREATED: FRIDAY, AUGUST 10, 2012
REM ***** MAIN SOURCE FILE *****

REM **** Conversion in Progress ****


NUMBER_OF_DECKS = 4
MAXPLAYERS = 4
TRUE = 1
FALSE = 0
LASTPLAYER = 0
DIM CARDIMAGE$(56) 
CARDBACKIMAGE$ = "         "
DIM BJCARDVALUE(56 * 10) 
DIM PKCARDVALUE(56 * 10) 
DIM CARDSUITVALUE(56 * 10) 
DIM CARDORDER(56 * 10) AS INTEGER
DIM CARDIMG(60) 
DIM MODE_RES_X(64) 
DIM MODE_RES_Y(64) 
DIM MODE_BITDEPTH(64) 
DISPPLAYERSPACING = 0
DISPPLAYERLEFT = 0
DISPPLAYERTOP = 0
DISPPLAYERVERTICAL = 0
SELECTED_BITDEPTH = 0
SELECTED_RES_X = 0
SELECTED_RES_Y = 0
DEALERHIDDEN = 0
CARDNO = 0
RESHUFFLENO = 0
NEWCARDVALUE = 0
ROUNDSPLAYED = 0
PLAYERNO = 0
GONEXTPLAYER = 0
ALLOWSPLIT = 0
EXITGAME = 0
DIM PLAYERNNAME$(4)
DIM PLAYERNDRAWN(4) 
DIM PLAYERNTOTAL(4,3) 
DIM PLAYERNCASH%(4) 
DIM PLAYERNBETENTERY%(4) 
DIM PLAYERNBET%(4) 
DIM PLAYERNSPLIT(4) = 0
DIM PLAYERNACES(4) = 0
DIM PLAYERBJCARDVAL(4, 20) 
DIM PLAYERPKCARDVAL(4, 20) 
DIM PLAYERSUCARDVAL(4, 20) 
DIM PLAYERNSPLITCARD(4, 20)
DIM PLAYERNDOUBLEUSED(4) 
DIM PLAYERNMESSAGE$(4) 
DOUBLEDOWNSET = 0
DOUBLEDOWN3UP = 0
SPLITSET = 0
BONUS777 = 0
BONUS678 = 0
DEALER17TIEWINS = 0
DEALERSOFT17HIT = 0 // IF DEALER HAS ONE ACE
DEALERNOHIDDEN = 0
CARDCHARLIEWINSET = 0
ALLOWSURRENDER = 0 // PLAYER GETS BACK HALF BET
SUIT21BONUS = 0
COLOR21BONUS = 0
SUITEDAJBONUS = 0 // ACE + JACK PAY IN SAME SUIT 2:1
JOKERBETRETURN = 0 
JOKERSPECIALACE = 0
JOKERSPRESANT = 0
DIM PLAYERNWINS(4) 
TOTALCARDS = 0
DECKSIZE = 0
SUITSIZE = 0
SS = 0   
END_PROGRAM = 0
A=0
B=0
C=0
D=0
E=0 
F=0 
G=0 
H=0 
I=0 
J=0 
K=0 
L=0
M=0
N=0
O=0
P=0
Q=0
R=0
S=0
T=0
U=0
V=0
W=0
X=0
Y=0
Z=0
END_PROGRAM = FALSE

REPEAT
    EXEC INIT_DEFAULTS
    EXEC DOSETTINGS
    IF END_PROGRAM = FALSE
        EXEC INIT_GAME
        EXEC SHOWSTATS
        EXEC SHOW ALL SPRITES
        EXEC SHUFFLEDECKS    
        EXITGAME = FALSE
        REPEAT
            GETBETS
            IF EXITGAME = FALSE
                PLAYERNO = 0
                EXEC SHOW ALL SPRITES
                EXEC DODEAL
                IF PLAYERNO <= LASTPLAYER
                    REPEAT
                        DOPLAYERINPUT
                        IF PLAYERNSPLIT(PLAYERNO) = 2 
                            DONEXTHAND                        
                        ELSE
                            PLAYERNO = PLAYERNO + 1
                        ENDIF
                    UNTIL PLAYERNO >LASTPLAYER    
                ENDIF
                PLAYERNO =0 
                EXEC DODEALER
                EXEC DOREWARDS
                REPEAT
                    EXEC SHOWSTATS
                       IF UPPER$(INKEY$) = "S" AND SSOK=0
                               GET IMAGE 999,0,0,SELECTED_RES_X,SELECTED_RES_Y,3
                               F$="IMGBLACKJACK" + (STR$(INT(SS/10))) + (STR$(SS MOD 10)) + ".BMP"
                               SAVE IMAGE F$,999
                               SS=SS+1
                               IF SS>9 THEN SS=0
                        ENDIF 
                UNTIL INKEY$ = " " OR MOUSECLICK>=1
                EXEC SHOW ALL SPRITES
                FOR I = 0 TO CARDNO 
                    J = CARDORDER(I) 
                    SPRITE J+1, -200, -200, CARDIMAGE(J)
                NEXT I
                IF CARDNO >= RESHUFFLENO THEN EXEC SHUFFLEDECKS
            ENDIF
        UNTIL EXITGAME = TRUE
    ENDIF
UNTIL END_PROGRAM = TRUE

END

PROC INIT_GAME
        LOCAL DECK AS BYTE
        LOCAL CARDPLACE AS INTEGER
        LOCAL IMAGEGET AS INTEGER
        LOCAL LASTCARD AS INTEGER
        LOCAL FILENUMBERSTRING$ AS STRING        
        EXEC SET WINDOW OFF
        SET DISPLAY MODE SELECTED_RES_X, SELECTED_RES_Y, SELECTED_BITDEPTH
        COLOR BACKDROP RGB(16,64,16)
        IF SELECTED_RES_Y > 300 AND SELECTED_RES_Y < 621
            DISPPLAYERTOP = 244
            DISPPLAYERVERTICAL = 27
        ENDIF
        IF SELECTED_RES_Y > 620 AND SELECTED_RES_Y < 780 
            DISPPLAYERTOP = 248
            DISPPLAYERVERTICAL = 28
        ENDIF
        IF SELECTED_RES_Y >= 779 AND SELECTED_RES_Y < 1000 
            DISPPLAYERTOP = 280
            DISPPLAYERVERTICAL = 30
        ENDIF
        IF SELECTED_RES_Y > 999
            DISPPLAYERTOP = 320
            DISPPLAYERVERTICAL = 32
        ENDIF
        IF LASTPLAYER = 1 
            DISPPLAYERSPACING = 250
            DISPPLAYERLEFT = 150
        ELSE            
            IF LASTPLAYER >= 4 
                DISPPLAYERSPACING = (SELECTED_RES_X - 120) / LASTPLAYER
                DISPPLAYERLEFT = 50
             ELSE
                DISPPLAYERSPACING = (SELECTED_RES_X - 160) / LASTPLAYER
                DISPPLAYERLEFT = 75
             ENDIF            
             IF DISPPLAYERSPACING <= 270
                DISPPLAYERSPACING = 270
                DISPPLAYERLEFT = 25
             ENDIF
        ENDIF 
        
        AUTOCAM OFF
        RANDOMIZE -TIMER
        IF DECKSIZE = 56
            LASTCARD = 55
            SUITSIZE = 13
         ELIF DECKSIZE = 52
            LASTCARD = 51            
            SUITSIZE = 13
         ELIF DECKSIZE = 48
            LASTCARD = 47
            SUITSIZE = 12
         ENDIF
        TOTALCARDS = DECKSIZE * NUMBER_OF_DECKS - 1        
        RESHUFFLENO = TOTALCARDS - 22
        IF LASTPLAYER >= 4 AND NUMBEROFDECKS >=6 THEN RESHUFFLENO = TOTALCARDS - 28
        FOR CARDPLACE = 1 TO 64
            FILENUMBERSTRING$ = RIGHT$("0" + STR$(CARDPLACE),2)
            IF DECKSIZE = 52 OR DECKSIZE = 56 OR (CARDPLACE MOD 13) <> 10
                LOAD IMAGE "CARD" + FILENUMBERSTRING$ + ".BMP", CARDPLACE                                 
            ENDIF
        NEXT CARDPLACE        
        CARDNO = 0 
        IMAGEGET = 1
        FOR CARDPLACE = 0 TO LASTCARD
            IF (CARDPLACE MOD SUITSIZE) = 0 THEN RESTORE BLACKJACKVALUES            
            READ V
            IF CARDPLACE >=53 THEN V = 11
            BJCARDVALUE(CARDPLACE) = V
            CARDSUITVALUE(CARDPLACE) = 1 + INT(CARDPLACE / SUITSIZE)
            CARDIMAGE(CARDNO) = IMAGEGET
//            PASTE IMAGE CARDIMAGE(CARDNO), ((CARDNO) MOD SUITSIZE) * 72,INT((CARDNO) / SUITSIZE) * 112
            // PRINT CARDIMAGE(CARDNO)
            SPRITE CARDNO + 1, 0, 0, CARDIMAGE(CARDNO)
            OFFSET SPRITE CARDNO + 1, 35.5, 48
            //OFFSET SPRITE CARDNO + 1, 25.5, 36
            CARDNO = CARDNO + 1
            IMAGEGET = IMAGEGET + 1 
            IF DECKSIZE = 48 AND (CARDPLACE MOD SUITSIZE) = 8
                 READ V
                 IMAGEGET = IMAGEGET + 1
            ENDIF
        NEXT CARDPLACE
        FOR CARDPLACE = 0 TO LASTCARD
            IF (CARDPLACE MOD SUITSIZE) = 0 THEN RESTORE POKERVALUES
            READ V                
            IF DECKSIZE = 56 AND CARDPLACE >= 53 THEN V = 11
            IF DECKSIZE = 52 AND V >  11 THEN V = V - 1
            IF DECKSIZE = 48 AND V >  9 THEN V = V - 2            
            PKCARDVALUE(CARDPLACE) = V
             SET CURSOR ((CARDPLACE) MOD SUITSIZE) * 72 + 20,INT((CARDPLACE) / SUITSIZE) * 112 + 98
             // PRINT V            
        NEXT CARDPLACE            
        CARDNO = DECKSIZE
        JOKERSPRESANT = 0
        FOR DECK = 1 TO NUMBER_OF_DECKS
            FOR CARDPLACE = 0 TO LASTCARD
                BJCARDVALUE(CARDNO) = BJCARDVALUE(CARDPLACE)
                PKCARDVALUE(CARDNO) = PKCARDVALUE(CARDPLACE)
                CARDIMAGE(CARDNO) = CARDIMAGE(CARDPLACE)
                CARDSUITVALUE(CARDNO) = CARDSUITVALUE(CARDPLACE)
                SPRITE CARDNO + 1, -200, -200, CARDIMAGE(CARDNO)
                OFFSET SPRITE CARDNO + 1, 35.5, 48                                        
                //OFFSET SPRITE CARDNO + 1, 27.5, 40
                // OFFSET SPRITE CARDNO + 1, 25.5, 36
                CARDNO = CARDNO + 1
            NEXT CARDPLACE
        NEXT DECK
        FOR N = 0 TO TOTALCARDS + JOKERSPRESANT
            SPRITE N + 1, -200, -200, CARDIMAGE(N)                        
        NEXT N
        HIDE ALL SPRITES
        IF DECKSIZE = 56 THEN SUITSIZE = 14
        BACKDROP OFF
        FOR N = 1 TO MAXPLAYERS
            PLAYERNCASH(N) = 5000
            PLAYERNBET(N) = 0
        NEXT N
BLACKJACKVALUES:
        DATA 11,2,3,4,5,6,7,8,9,10,10,10,10,11
POKERVALUES:
        DATA 15,2,3,4,5,6,7,8,9,10,12,13,14,11
ENDROC

PROC CALCTOTAL
    LOCAL TOTAL AS INTEGER
    LOCAL ACES AS INTEGER
    F = 0
    TOTAL = 0
    ACES = 0
    PLAYERNACES(PLAYERNO) = 0
    IF PLAYERNSPLIT(PLAYERNO) <= 2
        F = 0
    ENDIF
    IF PLAYERNSPLIT(PLAYERNO) = 3
        F = 7
    ENDIF
    IF PLAYERNSPLIT(PLAYERNO) = 4
        F = 14
    ENDIF
    FOR I = F TO PLAYERNDRAWN(PLAYERNO) - 1
        TOTAL = TOTAL + PLAYERBJCARDVAL(PLAYERNO, I)
        IF PLAYERBJCARDVAL(PLAYERNO, I) = 11 
            ACES = ACES + 1
            PLAYERNACES(PLAYERNO) = PLAYERNACES(PLAYERNO) + 1
         ENDIF
    NEXT I
    // CHECK IF THERE ARE ANY ACES WHEN A TOTAL IS MORE THAN 21, IF SO, SUBRACT 10 UNTIL NO MORE ACES OR LESS THAN 22.
    IF ACES > 0
        FOR I = 0 TO ACES - 1 
            IF TOTAL > 21 THEN TOTAL = TOTAL - 10
        NEXT I
    ENDIF
    IF PLAYERNSPLIT(PLAYERNO) <= 2 
        PLAYERNTOTAL(PLAYERNO,0) = TOTAL
    ENDIF
    IF PLAYERNSPLIT(PLAYERNO) = 3         
        PLAYERNTOTAL(PLAYERNO,1) = TOTAL
    ENDIF
ENDROC

PROC DODEAL
    LOCAL PLAYERNUMBER AS INTEGER
    LOCAL USEIMAGE AS INTEGER
    LOCAL CARDSPACING AS INTEGER 
    CARDSPACING = 16
    ROUNDSPLAYED = ROUNDSPLAYED + 1
    CLS
    SHOWSTATS
    IF PLAYERNSPLIT(PLAYERNO) >= 2 THEN CARDSPACING = 14
    FOR PLAYERNUMBER = 0 TO LASTPLAYER
        FOR N = 0 TO 20
            PLAYERBJCARDVAL(PLAYERNUMBER, N) = 0
            PLAYERPKCARDVAL(PLAYERNUMBER, N) = 0
        NEXT N
        PLAYERNO = PLAYERNUMBER
        PLAYERNMESSAGE$(PLAYERNO) = ""
        PLAYERNSPLIT(PLAYERNO) = 0
        PLAYERNTOTAL(PLAYERNO,0) = 0
        PLAYERNTOTAL(PLAYERNO,1) = 0
        PLAYERNTOTAL(PLAYERNO,2) = 0
        PLAYERNTOTAL(PLAYERNO,3) = 0
        PLAYERNACES(PLAYERNO) = 0
        PLAYERNDOUBLEUSED(PLAYERNO) = 0
        PLAYERNSPLITCARD(PLAYERNO) = 0
         FOR N = 0 TO 1
             IF PLAYERNO = 0 
                 G = SELECTED_RES_X * .52 + 4 + 16 * N                 
                 IF SELECTED_RES_Y < 640 
                    H = 58 + 10 * N
                 ELSE
                    H = 64 + 12 * N
                 ENDIF
                 IF N = 1
                    USEIMAGE = CARDBACKIMAGE 
                    DEALERHIDDEN = CARDNO
                 ELSE
                    USEIMAGE = CARDIMAGE(CARDORDER(CARDNO))
                 ENDIF
             ELSE                 
                 G = DISPPLAYERLEFT + (PLAYERNUMBER - 1) * DISPPLAYERSPACING + 10 + CARDSPACING * N
                 H = DISPPLAYERTOP + DISPPLAYERVERTICAL * 0 + 12 * N
                 IF SELECTED_RES_Y < 640 THEN H = DISPPLAYERTOP + DISPPLAYERVERTICAL * 0 + 10 * N
                 USEIMAGE = CARDIMAGE(CARDORDER(CARDNO))
             ENDIF
             ANIMATEHIT(CARDORDER(CARDNO), G, H, USEIMAGE)
             NEWCARDVALUE = BJCARDVALUE(CARDORDER(CARDNO))
             PLAYERBJCARDVAL(PLAYERNO, N) = NEWCARDVALUE
             PLAYERPKCARDVAL(PLAYERNO, N) = PKCARDVALUE(CARDORDER(CARDNO))
             PLAYERSUCARDVAL(PLAYERNO, N) = CARDSUITVALUE(CARDORDER(CARDNO))
             IF PLAYERNO > 0              
                IF N = 0 
                    SELECT SPLITSET
                        CASE 0 // CAN SPLIT EITHER TEN, JACK, QUEEN, OR KING)
                            F = BJCARDVALUE(CARDORDER(CARDNO))
                        ENDCASE
                        CASE 1 // SPLIT EXACT PAIR (2 TENS, JACKS, QUEENS, OR KING)
                            F = PKCARDVALUE(CARDORDER(CARDNO))
                        ENDCASE                        
                        CASE 2 // NO SPLIT ACES AND EXACT PAIR
                            IF BJCARDVALUE(CARDNO) < 11 
                                F = PKCARDVALUE(CARDORDER(CARDNO))
                            ELSE
                                F = 255
                            ENDIF
                        ENDCASE
                    ENDSELECT
                 ENDIF
                 IF N = 1 
                    SELECT SPLITSET     
                        CASE 0 // CAN SPLIT EITHER TEN, JACK, QUEEN, OR KING)
                            E = BJCARDVALUE(CARDORDER(CARDNO))
                        ENDCASE
                        CASE 1 // SPLIT EXACT PAIR (2 TENS, JACKS, QUEENS, OR KING)
                            E = PKCARDVALUE(CARDORDER(CARDNO))
                        ENDCASE                        
                        CASE 2 // NO SPLIT ACES AND EXACT PAIR
                            IF BJCARDVALUE(CARDNO) < 11 
                                E = PKCARDVALUE(CARDORDER(CARDNO))
                            ELSE
                                E = 254 // 255 WILL NOT EQUAL 254
                            ENDIF
                        ENDCASE
                     ENDSELECT
                     IF E = F 
                        PLAYERNSPLIT(PLAYERNO) = 1
                        PLAYERNSPLITCARD(PLAYERNO) = CARDORDER(CARDNO)
                     ENDIF
                 ENDIF
             ENDIF
             CARDNO = CARDNO + 1
        NEXT N
        PLAYERNDRAWN(PLAYERNO) = 2
        IF PLAYERNO = 0 
             EXEC CALCTOTAL
        ELSE
             EXEC CALCTOTAL        
             IF PLAYERNTOTAL(PLAYERNO,0) = 21 
               PLAYERNMESSAGE$(PLAYERNO) = "TOTAL : 21  BLACKJACK"               
             ELSE
                PLAYERNMESSAGE$(PLAYERNO) = "TOTAL:" + STR$(PLAYERNTOTAL(PLAYERNO,0))
             ENDIF
             SHOWSTATS
        ENDIF
    NEXT PLAYERNUMBER
    PLAYERNO = 1
    IF PLAYERNTOTAL(1,0) = 21 
        PLAYERNO = 2
        IF PLAYERNTOTAL(2,0) = 21 
            PLAYERNO = 3
            IF PLAYERNTOTAL(3,0) = 21 
                PLAYERNO = 4
                IF PLAYERNTOTAL(4,0) = 21 THEN PLAYERNO = MAXPLAYERS + 1
            ENDIF
        ENDIF
    ENDIF
    IF PLAYERNTOTAL(0,0) = 21 
        IF PLAYERBJCARDVAL(0,0) = 11 THEN PLAYERNO = MAXPLAYERS + 1
    ENDIF
ENDROC

PROC ANIMATEHIT(CARDNOIN, CARDDESTX , CARDDESTY, IMAGENOIN)
   LOCAL CARDPOSX AS FLOAT
   LOCAL CARDPOSY AS FLOAT
   LOCAL CARDDIR AS FLOAT
   LOCAL CARDDIST AS FLOAT
   LOCAL CARDROTSTEP AS FLOAT
   LOCAL CARDROTCURR AS FLOAT
   LOCAL DN AS INTEGER
   CARDPOSX = SELECTED_RES_X / 2
   CARDPOSY = -24
   CARDDIR = ATANFULL(CARDDESTX-CARDPOSX,CARDDESTY-CARDPOSY)
   CARDDIST = SQRT((CARDPOSX-CARDDESTX)^2 + (CARDPOSY-CARDDESTY)^2)
   CARDROTSTEP = 360 / (CARDDIST * .03125)
   N = INT(CARDDIST / 32) - 1
   SET SPRITE PRIORITY CARDNOIN+1, CARDNO
   REPEAT
       SPRITE CARDNOIN+1, CARDPOSX, CARDPOSY, IMAGENOIN
       ROTATE SPRITE CARDNOIN+1, CARDROTCURR 
       SHOWSTATS
       CARDPOSX = CARDPOSX + SIN(CARDDIR) * 32
       CARDPOSY = CARDPOSY + COS(CARDDIR) * 32
       CARDROTCURR =  CARDROTCURR  + CARDROTSTEP
       N = N - 1
   UNTIL N<=0
   SPRITE CARDNOIN+1, CARDDESTX, CARDDESTY, IMAGENOIN
   ROTATE SPRITE CARDNOIN+1, 0
ENDROC

PROC DOPLAYERINPUT
    LOCAL KEYPRESSED$ = ""
    LOCAL KEYUP AS BOOLEAN = TRUE
    LOCAL MX AS INTEGER
    LOCAL MY AS INTEGER
    LOCAL DN AS INTEGER
    GONEXTPLAYER = FALSE
    PLAYERNDOUBLEUSED(PLAYERNO) = 0
    CLS
    REPEAT         
        SHOWSTATS
        MX=MOUSEX
        MY=MOUSEY
        IF PLAYERNCASH(PLAYERNO) < PLAYERNBET(PLAYERNO) THEN PLAYERNDOUBLEUSED(PLAYERNO) = 1
        IF DOUBLEDOWNSET = 1 AND (PLAYERNTOTAL(PLAYERNO,0) <=9 OR PLAYERNTOTAL(PLAYERNO,0)>=12) THEN PLAYERNDOUBLEUSED(PLAYERNO) = 1
        IF DOUBLEDOWNSET = 2 AND (PLAYERNTOTAL(PLAYERNO,0) <=8 OR PLAYERNTOTAL(PLAYERNO,0)>=12) THEN PLAYERNDOUBLEUSED(PLAYERNO) = 1
        IF (PLAYERNTOTAL(PLAYERNO,0) < 21 OR (PLAYERNSPLIT(PLAYERNO) = 3) AND PLAYERNTOTAL(PLAYERNO,1) <21)
            SHOWCOMMANDS             
            IF INKEY$<>"" OR MOUSECLICK >= 1
                KEYUP = FALSE
                KEYPRESSED$ = UPPER$(INKEY$)
                DN = -2
                IF MOUSECLICK >= 1  THEN DN = PLAYERNO - 1    
                IF MX > DISPPLAYERLEFT + SPLITEXTRALEFT  + 5 + DISPPLAYERSPACING * DN AND MY > DISPPLAYERTOP + DISPPLAYERVERTICAL * 10 - 1 AND MX < DISPPLAYERLEFT + SPLITEXTRALEFT  + 105 + DISPPLAYERSPACING * DN AND MY < DISPPLAYERTOP + DISPPLAYERVERTICAL * 10 + 21 THEN KEYPRESSED$ = "H"
                IF MX > DISPPLAYERLEFT + SPLITEXTRALEFT  + 118 + DISPPLAYERSPACING * DN AND MY > DISPPLAYERTOP + DISPPLAYERVERTICAL * 10 - 1 AND MX < DISPPLAYERLEFT + SPLITEXTRALEFT  + 217 + DISPPLAYERSPACING * DN AND MY < DISPPLAYERTOP + DISPPLAYERVERTICAL * 10 + 21 THEN KEYPRESSED$ = "S"
                IF MX > DISPPLAYERLEFT + SPLITEXTRALEFT  + 5 + DISPPLAYERSPACING * DN AND MY > DISPPLAYERTOP + DISPPLAYERVERTICAL * 11 - 1 AND MX < DISPPLAYERLEFT + SPLITEXTRALEFT  + 105 + DISPPLAYERSPACING * DN AND MY < DISPPLAYERTOP + DISPPLAYERVERTICAL * 11 + 21 THEN  KEYPRESSED$ = "D" 
                IF PLAYERNSPLIT(PLAYERNO) = 1 AND PLAYERNDRAWN(PLAYERNO) <= 2
                    IF MX > DISPPLAYERLEFT + SPLITEXTRALEFT  + 118 + DISPPLAYERSPACING * DN AND MY > DISPPLAYERTOP + DISPPLAYERVERTICAL * 11 - 1 AND MX < DISPPLAYERLEFT + SPLITEXTRALEFT  + 217 + DISPPLAYERSPACING * DN AND MY < DISPPLAYERTOP + DISPPLAYERVERTICAL * 11 + 21 THEN KEYPRESSED$ = "T" 
                ENDIF    
                IF ALLOWSURRENDER = TRUE AND PLAYERNDRAWN(PLAYERNO) = 2 AND PLAYERNSPLIT(PLAYERNO) <= 1
                    IF MX > DISPPLAYERLEFT + SPLITEXTRALEFT  + 5 + DISPPLAYERSPACING * DN AND MY > DISPPLAYERTOP + DISPPLAYERVERTICAL * 12 - 1 AND MX < DISPPLAYERLEFT + SPLITEXTRALEFT  + 139 + DISPPLAYERSPACING * DN AND MY < DISPPLAYERTOP + DISPPLAYERVERTICAL * 12 + 21 THEN KEYPRESSED$ = "U" 
                ENDIF
            ELSE
                IF INKEY$ = "" AND KEYUP = FALSE AND MOUSECLICK = 0
                    
                    
                    KEYUP = TRUE
                    IF KEYPRESSED$ = "H" 
                        EXEC DOHIT
                        IF PLAYERNDRAWN(PLAYERNO) >=3 AND DOUBLEDOWN3UP = FALSE THEN PLAYERNDOUBLEUSED(PLAYERNO) = 1
                        IF PLAYERNDRAWN(PLAYERNO) >=4 AND DOUBLEDOWN3UP = TRUE THEN PLAYERNDOUBLEUSED(PLAYERNO) = 1
                    ENDIF
                    IF KEYPRESSED$ = "S" 
                        GONEXTPLAYER = TRUE
                        IF PLAYERNSPLIT(PLAYERNO) <= 1 
                            PLAYERNMESSAGE$(PLAYERNO) = "TOTAL:" + STR$(PLAYERNTOTAL(PLAYERNO,0)) + "  STANDING"                
                        ENDIF
                        IF PLAYERNSPLIT(PLAYERNO) = 2                             
                            PLAYERNMESSAGE$(PLAYERNO) = "T:" + STR$(PLAYERNTOTAL(PLAYERNO,0)) + " STAND|T:" + STR$(PLAYERNTOTAL(PLAYERNO,1))
                        ENDIF
                        IF PLAYERNSPLIT(PLAYERNO) = 3
                            PLAYERNMESSAGE$(PLAYERNO) = "T:" + STR$(PLAYERNTOTAL(PLAYERNO,0)) + "|T:" + STR$(PLAYERNTOTAL(PLAYERNO,1)) + " STAND"
                        ENDIF
                    ENDIF
                    IF KEYPRESSED$ = "D" AND PLAYERNDOUBLEUSED(PLAYERNO) = 0
                        PLAYERNBET(PLAYERNO) = PLAYERNBET(PLAYERNO) * 2
                        EXEC DOHIT
                        GONEXTPLAYER = TRUE
                        PLAYERNDOUBLEUSED(PLAYERNO) = 1
                    ENDIF
                    IF KEYPRESSED$ = "T" AND PLAYERNSPLIT(PLAYERNO) <= 1 
                        DOSPLITDEAL
                    ENDIF
                    IF KEYPRESSED$ = "U" AND ALLOWSURRENDER = TRUE AND PLAYERNDRAWN(PLAYERNO) = 2 AND PLAYERNSPLIT(PLAYERNO) <= 1 
                        PLAYERNDRAWN(PLAYERNO) = - PLAYERNDRAWN(PLAYERNO)                
                        PLAYERNMESSAGE$(PLAYERNO) = "SURRENDERED"
                        GONEXTPLAYER = TRUE
                    ENDIF
                    IF KEYPRESSED$ = "Q" 
                        GONEXTPLAYER = TRUE
                    ENDIF
                    KEYPRESSED$ = ""
                 ENDIF
             ENDIF 
          ELSE
             GONEXTPLAYER = TRUE
          ENDIF
    UNTIL GONEXTPLAYER = TRUE
ENDROC

PROC DODEALER
    Z = 100
    G = SELECTED_RES_X * .52 + 4 + 16 
    REPEAT
        Z = Z - 2
        STRETCH SPRITE CARDORDER(DEALERHIDDEN)+ 1,Z, 100        
    UNTIL Z<=2
    IF SELECTED_RES_Y < 640
        H = 58 + 10
    ELSE
        H = 64 + 12 
    ENDIF
    SPRITE CARDORDER(DEALERHIDDEN)+ 1, G, H, CARDIMAGE(CARDORDER(DEALERHIDDEN))
    REPEAT
        Z = Z + 2
        STRETCH SPRITE CARDORDER(DEALERHIDDEN)+ 1,Z, 100        
    UNTIL Z>=100
    EXEC CALCTOTAL
    PLAYERNO = 0
    IF PLAYERNTOTAL(0,0) < 21 
        REPEAT 
            IF DEALERSOFT17HIT = FALSE     
                IF PLAYERNTOTAL(0,0) <= 16 THEN EXEC DOHIT 
            ELSE
                IF PLAYERNTOTAL(0,0) <= 16 THEN EXEC DOHIT 
                EXEC CALCTOTAL
                IF PLAYERNTOTAL(0,0) = 17 AND PLAYERNACES(0) > 0 THEN EXEC DOHIT
                EXEC CALCTOTAL
            ENDIF                
        UNTIL PLAYERNTOTAL(0,0) >= 17
        IF PLAYERNTOTAL(0,0) <=21 
            PLAYERNMESSAGE$(0) = "TOTAL:" + STR$(PLAYERNTOTAL(0,0)) + "   STANDING"
        ELSE
            PLAYERNMESSAGE$(0) = "TOTAL:" + STR$(PLAYERNTOTAL(0,0)) + "   BUSTED"
        ENDIF        
    ELSE:IF PLAYERNDRAWN(0) = 2 AND PLAYERNTOTAL(0,0) = 21  
        PLAYERNMESSAGE$(0) = "TOTAL:" + STR$(PLAYERNTOTAL(0,0)) + "  BLACKJACK"
    ENDIF:ENDIF
    SHOWSTATS
ENDROC

PROC DOHIT
    LOCAL CARDSPACING AS INTEGER 
    CARDSPACING = 16    
    PLAYERNUMBER = PLAYERNO
    N = PLAYERNDRAWN(PLAYERNUMBER)
    IF PLAYERNUMBER = 0 
         N = PLAYERNDRAWN(0)
         G = SELECTED_RES_X * .52 + 4 + 16 * N                  
         IF SELECTED_RES_Y < 640
            H = 58 + 10 * N
         ELSE
            H = 64 + 12 * N
         ENDIF
         USEIMAGE = CARDIMAGE(CARDORDER(CARDNO))
    ELSE                 
         IF PLAYERNSPLIT(PLAYERNO) >= 2 THEN CARDSPACING = 14
         IF PLAYERNSPLIT(PLAYERNO) < 3 
            G = DISPPLAYERLEFT + (PLAYERNO - 1) * DISPPLAYERSPACING + 10 + CARDSPACING * N
            H = DISPPLAYERTOP + DISPPLAYERVERTICAL * 0 + 12 * N
            IF SELECTED_RES_Y < 640 THEN H = DISPPLAYERTOP + DISPPLAYERVERTICAL * 0 + 10 * N
         ELSE:IF PLAYERNSPLIT(PLAYERNO) = 3 
            N = PLAYERNDRAWN(PLAYERNUMBER) - 7
            G = DISPPLAYERLEFT + (PLAYERNO - 1) * DISPPLAYERSPACING + 78 + INT(DISPPLAYERSPACING * .11) + CARDSPACING * N
            H = DISPPLAYERTOP + DISPPLAYERVERTICAL * 0 + 12 * N
            IF SELECTED_RES_Y < 640 THEN H = DISPPLAYERTOP + DISPPLAYERVERTICAL * 0 + 10 * N
         ENDIF:ENDIF         
         USEIMAGE = CARDIMAGE(CARDORDER(CARDNO))
    ENDIF
    ANIMATEHIT(CARDORDER(CARDNO), G, H, USEIMAGE)
    NEWCARDVALUE = BJCARDVALUE(CARDORDER(CARDNO))
    PLAYERBJCARDVAL(PLAYERNO, PLAYERNDRAWN(PLAYERNO)) = NEWCARDVALUE
    PLAYERPKCARDVAL(PLAYERNO, PLAYERNDRAWN(PLAYERNO)) = PKCARDVALUE(CARDORDER(CARDNO))
    PLAYERSUCARDVAL(PLAYERNO, PLAYERNDRAWN(PLAYERNO)) = CARDSUITVALUE(CARDORDER(CARDNO))
    CARDNO = CARDNO + 1
    PLAYERNDRAWN(PLAYERNO) = PLAYERNDRAWN(PLAYERNO) + 1
    EXEC CALCTOTAL
    IF PLAYERNSPLIT(PLAYERNO) <> 3 
        // BLACKJACKFORM.PLAYERTOTALSHOW(PLAYERNO).TEXT = CSTR(PLAYERNTOTAL(PLAYERNO,0))
    ELSE
        // BLACKJACKFORM.PLAYERTOTALSHOW(PLAYERNO).TEXT = PLAYERNTOTAL(PLAYERNO,1) & "|T:" & PLAYERNTOTAL(PLAYERNO,0)
    ENDIF
    IF PLAYERNTOTAL(PLAYERNO,0) >= 22 
        IF PLAYERNSPLIT(PLAYERNO) < 2 
            PLAYERNMESSAGE$(PLAYERNO) = "TOTAL:" + STR$(PLAYERNTOTAL(PLAYERNO,0)) + "  BUSTED"
            GONEXTPLAYER = TRUE
        ENDIF
        IF PLAYERNSPLIT(PLAYERNO) >= 2 AND PLAYERNTOTAL(PLAYERNO,1) < 22
            PLAYERNMESSAGE$(PLAYERNO) = "T:" + STR$(PLAYERNTOTAL(PLAYERNO,0)) + " BUST|T:"  + STR$(PLAYERNTOTAL(PLAYERNO,1))       
            IF PLAYERNSPLIT(PLAYERNO) = 2 THEN GONEXTPLAYER = TRUE
        ENDIF
        IF PLAYERNSPLIT(PLAYERNO) = 3 AND PLAYERNTOTAL(PLAYERNO,1) >= 22
            PLAYERNMESSAGE$(PLAYERNO) = "T:" + STR$(PLAYERNTOTAL(PLAYERNO,0)) + "|T:"  + STR$(PLAYERNTOTAL(PLAYERNO,1)) + " BUST"
        ENDIF
    ELSE
        IF PLAYERNSPLIT(PLAYERNO) < 2 
            PLAYERNMESSAGE$(PLAYERNO) = "TOTAL:" + STR$(PLAYERNTOTAL(PLAYERNO,0))
        ELSE
            PLAYERNMESSAGE$(PLAYERNO) = "T:" + STR$(PLAYERNTOTAL(PLAYERNO,0)) + "|T:"  + STR$(PLAYERNTOTAL(PLAYERNO,1))
        ENDIF
        IF (PLAYERNDRAWN(PLAYERNO) = 6 OR PLAYERNDRAWN(PLAYERNO) = 13) AND CARDCHARLIEWINSET = 6
            IF PLAYERNSPLIT(PLAYERNO) < 2 
                PLAYERNMESSAGE$(PLAYERNO) = "TOTAL:" + STR$(PLAYERNTOTAL(PLAYERNO,0)) + " SIX CARD CHARLIE"
            ELSE
                PLAYERNMESSAGE$(PLAYERNO) = "T:" + STR$(PLAYERNTOTAL(PLAYERNO,0)) + " C6|T:"  + STR$(PLAYERNTOTAL(PLAYERNO,1))
            ENDIF
            GONEXTPLAYER = TRUE
        ENDIF
        IF (PLAYERNDRAWN(PLAYERNO) = 5 OR PLAYERNDRAWN(PLAYERNO) = 12) AND CARDCHARLIEWINSET = 5
            IF PLAYERNSPLIT(PLAYERNO) < 2 
                PLAYERNMESSAGE$(PLAYERNO) = "TOTAL:" + STR$(PLAYERNTOTAL(PLAYERNO,0)) + " FIVE CARD CHARLIE"
            ELSE
                PLAYERNMESSAGE$(PLAYERNO) = "T:" + STR$(PLAYERNTOTAL(PLAYERNO,0)) + " C5|T:"  + STR$(PLAYERNTOTAL(PLAYERNO,1))
            ENDIF
            GONEXTPLAYER = TRUE
        ENDIF
    ENDIF
ENDROC

PROC DOREWARDS
    LOCAL SPLITREWARD AS INTEGER
    LOCAL PLAYERNUMBER AS INTEGER
    LOCAL BONUSREWARD AS BOOLEAN = FALSE
    LOCAL C AS INTEGER
    LOCAL SPLITBASE AS INTEGER
    LOCAL DIM HANDREWARD(3) AS INTEGER
    LOCAL HANDNUMBER AS INTEGER
    LOCAL HANDTOTAL AS INTEGER
    SPLITREWARD = 0
    FOR PLAYERNUMBER = 1 TO LASTPLAYER
        PLAYERNO = PLAYERNUMBER
        HANDNUMBER = 0
        SPLITBASE = 0
        REPEAT
            IF PLAYERNDRAWN(PLAYERNO) >= 2
                PLAYERNDRAWN(PLAYERNO) = 0
                HANDREWARD(HANDNUMBER) = 0
                FOR C = 0 TO 6
                    IF PLAYERBJCARDVAL(PLAYERNO, SPLITBASE + C) > 0 THEN PLAYERNDRAWN(PLAYERNO) = PLAYERNDRAWN(PLAYERNO) + 1
                NEXT C
                IF HANDNUMBER = 0 THEN HANDTOTAL = PLAYERNTOTAL(PLAYERNO,0)
                IF HANDNUMBER = 1 THEN HANDTOTAL = PLAYERNTOTAL(PLAYERNO,1)
                IF HANDNUMBER = 2 THEN HANDTOTAL = PLAYERNTOTAL(PLAYERNO,2)
            ENDIF
            IF HANDTOTAL = 21 
                IF PLAYERNDRAWN(PLAYERNO) = 2 
                    C = 0
                    IF COLOR21BONUS = TRUE 
                        IF PLAYERSUCARDVAL(PLAYERNO, SPLITBASE +  0) = 2 OR PLAYERSUCARDVAL(PLAYERNO, SPLITBASE +  0) = 4 THEN C = C + 1
                        IF PLAYERSUCARDVAL(PLAYERNO, SPLITBASE +  1) = 2 OR PLAYERSUCARDVAL(PLAYERNO, SPLITBASE +  1) = 4 THEN C = C + 1
                        IF C = 2 
                            HANDREWARD(HANDNUMBER) = PLAYERNBET(PLAYERNO) * 2
                            IF HANDNUMBER = 0 THEN PLAYERNMESSAGE$(PLAYERNO) = "BLACKJACK BLACK  WON:" + STR$(PLAYERNBET(PLAYERNO) * 2)
                            PLAYERNWINS(PLAYERNO) = PLAYERNWINS(PLAYERNO) + 1
                        ELSE
                            C = 0
                            IF PLAYERSUCARDVAL(PLAYERNO, SPLITBASE +  0) = 1 OR PLAYERSUCARDVAL(PLAYERNO, SPLITBASE +  0) = 3 THEN C = C + 1
                            IF PLAYERSUCARDVAL(PLAYERNO, SPLITBASE +  1) = 1 OR PLAYERSUCARDVAL(PLAYERNO, SPLITBASE +  1) = 3 THEN C = C + 1
                            IF C = 2 
                                HANDREWARD(HANDNUMBER) =PLAYERNBET(PLAYERNO) * 2
                                IF HANDNUMBER = 0 THEN PLAYERNMESSAGE$(PLAYERNO) = "BLACKJACK RED  WON:" + STR$(PLAYERNBET(PLAYERNO) * 2)
                                PLAYERNWINS(PLAYERNO) = PLAYERNWINS(PLAYERNO) + 1
                            ELSE
                                C = 0
                            ENDIF
                        ENDIF
                    ENDIF
                    IF C = 0 
                        IF SUIT21BONUS = TRUE AND PLAYERSUCARDVAL(PLAYERNO, SPLITBASE +  0) = PLAYERSUCARDVAL(PLAYERNO, SPLITBASE +  1) 
                            HANDREWARD(HANDNUMBER) = PLAYERNBET(PLAYERNO) * 2
                            IF HANDNUMBER = 0 THEN PLAYERNMESSAGE$(PLAYERNO) = "SUITED BLACKJACK   WON:" + STR$(PLAYERNBET(PLAYERNO) * 2)
                            PLAYERNWINS(PLAYERNO) = PLAYERNWINS(PLAYERNO) + 1
                        ELSE
                            HANDREWARD(HANDNUMBER) = PLAYERNBET(PLAYERNO) * 1.5
                            IF HANDNUMBER = 0 THEN PLAYERNMESSAGE$(PLAYERNO) = "BLACKJACK   WON:" + STR$(PLAYERNBET(PLAYERNO) * 1.5)
                            PLAYERNWINS(PLAYERNO) = PLAYERNWINS(PLAYERNO) + 1
                        ENDIF
                    ENDIF
                ENDIF             
                IF PLAYERNDRAWN(PLAYERNO) = 3            
                    BONUSREWARD = FALSE            
                    IF BONUS777 = TRUE                                
                        C  = 0
                        IF PLAYERBJCARDVAL(PLAYERNO, SPLITBASE +  0) = 7 THEN C = C + 1
                        IF PLAYERBJCARDVAL(PLAYERNO, SPLITBASE +  1) = 7 THEN C = C + 1
                        IF PLAYERBJCARDVAL(PLAYERNO, SPLITBASE +  2) = 7 THEN C = C + 1                
                        IF C = 3
                            IF PLAYERSUCARDVAL(PLAYERNO, SPLITBASE +  0) = PLAYERSUCARDVAL(PLAYERNO, SPLITBASE +  1) AND PLAYERSUCARDVAL(PLAYERNO, SPLITBASE +  0) = PLAYERSUCARDVAL(PLAYERNO, SPLITBASE +  2) 
                                IF HANDNUMBER = 0 THEN PLAYERNMESSAGE$(PLAYERNO) = "21  SUITED 777 BONUS    WON:" + STR$(PLAYERNBET(PLAYERNO) * 4)
                                HANDREWARD(HANDNUMBER) =PLAYERNBET(PLAYERNO) * 4
                                BONUSREWARD = TRUE
                                PLAYERNWINS(PLAYERNO) = PLAYERNWINS(PLAYERNO) + 1
                            ELSE
                                IF HANDNUMBER = 0 THEN PLAYERNMESSAGE$(PLAYERNO) = "21  777 BONUS   WON:" + STR$(PLAYERNBET(PLAYERNO) * 3)
                                HANDREWARD(HANDNUMBER) = PLAYERNBET(PLAYERNO) * 3
                                BONUSREWARD = TRUE
                                PLAYERNWINS(PLAYERNO) = PLAYERNWINS(PLAYERNO) + 1
                            ENDIF
                        ELSE
                            IF PLAYERSUCARDVAL(PLAYERNO, SPLITBASE +  0) = PLAYERSUCARDVAL(PLAYERNO, SPLITBASE +  1) AND PLAYERSUCARDVAL(PLAYERNO, SPLITBASE +  0) = PLAYERSUCARDVAL(PLAYERNO, SPLITBASE +  2) AND SUIT21BONUS = TRUE AND BONUSREWARD = FALSE
                                IF HANDNUMBER = 0 THEN PLAYERNMESSAGE$(PLAYERNO) = "SUITED 21 BONUS    WON:" + STR$(PLAYERNBET(PLAYERNO) * 2)
                                HANDREWARD(HANDNUMBER) =PLAYERNBET(PLAYERNO) * 2
                                BONUSREWARD = TRUE                    
                                PLAYERNWINS(PLAYERNO) = PLAYERNWINS(PLAYERNO) + 1
                            ENDIF
                        ENDIF                
                    ENDIF 
                    IF BONUS678 = TRUE AND BONUSREWARD = FALSE
                        C  = 0
                        IF PLAYERBJCARDVAL(PLAYERNO, SPLITBASE +  0) = 6 OR PLAYERBJCARDVAL(PLAYERNO, SPLITBASE +  1)  = 6 OR PLAYERBJCARDVAL(PLAYERNO, SPLITBASE +  2)  = 6 THEN C = C + 1
                        IF PLAYERBJCARDVAL(PLAYERNO, SPLITBASE +  0) = 7 OR PLAYERBJCARDVAL(PLAYERNO, SPLITBASE +  1)  = 7 OR PLAYERBJCARDVAL(PLAYERNO, SPLITBASE +  2)  = 7 THEN C = C + 1
                        IF PLAYERBJCARDVAL(PLAYERNO, SPLITBASE +  0) = 8 OR PLAYERBJCARDVAL(PLAYERNO, SPLITBASE +  1)  = 8 OR PLAYERBJCARDVAL(PLAYERNO, SPLITBASE +  2)  = 8 THEN C = C + 1
                        IF C = 3 
                            IF PLAYERSUCARDVAL(PLAYERNO, SPLITBASE +  0) = PLAYERSUCARDVAL(PLAYERNO, SPLITBASE +  1) AND PLAYERSUCARDVAL(PLAYERNO, SPLITBASE +  0) = PLAYERSUCARDVAL(PLAYERNO, SPLITBASE +  2) 
                                IF HANDNUMBER = 0 THEN PLAYERNMESSAGE$(PLAYERNO) = "21  SUITED 678 BONUS   WON:" + STR$(PLAYERNBET(PLAYERNO) * 4)
                                HANDREWARD(HANDNUMBER) = PLAYERNBET(PLAYERNO) * 4
                                BONUSREWARD = TRUE
                                PLAYERNWINS(PLAYERNO) = PLAYERNWINS(PLAYERNO) + 1
                            ELSE  
                                IF HANDNUMBER = 0 THEN PLAYERNMESSAGE$(PLAYERNO) = "21  678 BONUS  WON:" + STR$(PLAYERNBET(PLAYERNO) * 3)
                                HANDREWARD(HANDNUMBER) = PLAYERNBET(PLAYERNO) * 3
                                BONUSREWARD = TRUE
                                PLAYERNWINS(PLAYERNO) = PLAYERNWINS(PLAYERNO) + 1
                            ENDIF
                        ELSE
                            IF PLAYERSUCARDVAL(PLAYERNO, SPLITBASE +  0) = PLAYERSUCARDVAL(PLAYERNO, SPLITBASE +  1) AND PLAYERSUCARDVAL(PLAYERNO, SPLITBASE +  0) = PLAYERSUCARDVAL(PLAYERNO, SPLITBASE +  2) AND SUIT21BONUS = TRUE AND BONUSREWARD = FALSE
                                IF HANDNUMBER = 0 THEN PLAYERNMESSAGE$(PLAYERNO) = "SUITED 21 BONUS  WON:" + STR$(PLAYERNBET(PLAYERNO) * 2)
                                HANDREWARD(HANDNUMBER) = PLAYERNBET(PLAYERNO) * 2
                                BONUSREWARD = TRUE                    
                                PLAYERNWINS(PLAYERNO) = PLAYERNWINS(PLAYERNO) + 1
                            ENDIF
                        ENDIF
                    ENDIF 
                    IF BONUSREWARD = FALSE OR PLAYERNDRAWN(PLAYERNO) >=4 
                        IF (HANDTOTAL > PLAYERNTOTAL(0,0) OR PLAYERNTOTAL(0,0) >= 22)  
                            IF HANDNUMBER = 0 THEN PLAYERNMESSAGE$(PLAYERNO) = "TOTAL :" + STR$(HANDTOTAL) + "  WON:" + STR$(PLAYERNBET(PLAYERNO))
                            HANDREWARD(HANDNUMBER) = PLAYERNBET(PLAYERNO) 
                            PLAYERNWINS(PLAYERNO) = PLAYERNWINS(PLAYERNO) + 1
                        ENDIF
                        IF HANDTOTAL = PLAYERNTOTAL(0,0) 
                            IF HANDNUMBER = 0 THEN PLAYERNMESSAGE$(PLAYERNO) = "TOTAL :" + STR$(HANDTOTAL) + "    PUSH"
                            HANDREWARD(HANDNUMBER) = 0
                        ENDIF
                    ENDIF            
                 ENDIF
            ELSE:IF HANDTOTAL >= 22 
               IF HANDNUMBER = 0 THEN PLAYERNMESSAGE$(PLAYERNO) = STR$(HANDTOTAL) +" BUSTED  LOST:" + STR$(PLAYERNBET(PLAYERNO))
                 HANDREWARD(HANDNUMBER) =- PLAYERNBET(PLAYERNO) 
            ELSE:IF PLAYERNDRAWN(PLAYERNO) <= -1 
                IF HANDNUMBER = 0 THEN PLAYERNMESSAGE$(PLAYERNO) = "SURRENDERED  LOST:" + STR$(INT(PLAYERNBET(PLAYERNO)/2))
                 HANDREWARD(HANDNUMBER) = - INT(PLAYERNBET(PLAYERNO) / 2)
            ELSE:IF HANDTOTAL < 22 
                IF PLAYERNDRAWN(PLAYERNO) >= CARDCHARLIEWINSET AND PLAYERNDRAWN(PLAYERNO) <= 7
                    IF HANDNUMBER = 0
                        IF CARDCHARLIEWINSET = 5 THEN PLAYERNMESSAGE$(PLAYERNO) = "FIVE CARD CHARLIE  WON:" + STR$(PLAYERNBET(PLAYERNO))
                        IF CARDCHARLIEWINSET = 6 THEN PLAYERNMESSAGE$(PLAYERNO) = "SIX CARD CHARLIE  WON:" + STR$(PLAYERNBET(PLAYERNO))
                    ENDIF
                    HANDREWARD(HANDNUMBER) = PLAYERNBET(PLAYERNO) 
                    PLAYERNWINS(PLAYERNO) = PLAYERNWINS(PLAYERNO) + 1
                ELSE
                    IF (HANDTOTAL > PLAYERNTOTAL(0,0) OR PLAYERNTOTAL(0,0) >= 22 OR PLAYERNDRAWN(PLAYERNO) >= CARDCHARLIEWINSET)
                        HANDREWARD(HANDNUMBER) = PLAYERNBET(PLAYERNO) 
                        IF HANDNUMBER = 0 THEN PLAYERNMESSAGE$(PLAYERNO) = "TOTAL:" + STR$(HANDTOTAL) + "   WON:" + STR$(PLAYERNBET(PLAYERNO))
                        PLAYERNWINS(PLAYERNO) = PLAYERNWINS(PLAYERNO) + 1
                    ENDIF
                    IF HANDTOTAL = PLAYERNTOTAL(0,0) AND PLAYERNTOTAL(0,0) < 22                      
                        IF DEALER17TIEWINS = TRUE AND PLAYERNTOTAL(0,0) = 17                     
                            IF HANDNUMBER = 0 THEN PLAYERNMESSAGE$(PLAYERNO) = "TIE:" + STR$(HANDTOTAL) + "  LOST:" + STR$(PLAYERNBET(PLAYERNO))
                            HANDREWARD(HANDNUMBER) =- PLAYERNBET(PLAYERNO) 
                        ELSE
                            PLAYERNMESSAGE$(PLAYERNO) = "TOTAL:" + STR$(HANDTOTAL) + "    PUSH"
                            HANDREWARD(HANDNUMBER) = 0
                        ENDIF
                    ENDIF                        
                    IF HANDTOTAL < PLAYERNTOTAL(0,0) AND PLAYERNTOTAL(0,0) < 22
                        IF HANDNUMBER = 0 THEN PLAYERNMESSAGE$(PLAYERNO) = "TOTAL:" + STR$(HANDTOTAL) + "  LOST:" + STR$(PLAYERNBET(PLAYERNO))
                        HANDREWARD(HANDNUMBER) =- PLAYERNBET(PLAYERNO) 
                    ENDIF
                ENDIF
            ENDIF:ENDIF:ENDIF:ENDIF
            IF HANDNUMBER = 1
                PLAYERNMESSAGE$(PLAYERNO) = "T:" + STR$(PLAYERNTOTAL(PLAYERNO,0))
                IF HANDREWARD(0) > 0 THEN PLAYERNMESSAGE$(PLAYERNO) = PLAYERNMESSAGE$(PLAYERNO) + " W:" + STR$(HANDREWARD(0))
                IF HANDREWARD(0) < 0 THEN PLAYERNMESSAGE$(PLAYERNO) = PLAYERNMESSAGE$(PLAYERNO) + " L:" + STR$(ABS(HANDREWARD(0)))
                IF HANDREWARD(0) = 0 THEN PLAYERNMESSAGE$(PLAYERNO) = PLAYERNMESSAGE$(PLAYERNO) + " P"
                PLAYERNMESSAGE$(PLAYERNO) = PLAYERNMESSAGE$(PLAYERNO) + "|T:" + STR$(PLAYERNTOTAL(PLAYERNO,1))
                IF HANDREWARD(1) > 0 THEN PLAYERNMESSAGE$(PLAYERNO) = PLAYERNMESSAGE$(PLAYERNO) + " W:" + STR$(HANDREWARD(1))
                IF HANDREWARD(1) < 0 THEN PLAYERNMESSAGE$(PLAYERNO) = PLAYERNMESSAGE$(PLAYERNO) + " L:" + STR$(ABS(HANDREWARD(1)))
                IF HANDREWARD(1) = 0 THEN PLAYERNMESSAGE$(PLAYERNO) = PLAYERNMESSAGE$(PLAYERNO) + " P"
            ENDIF
            SPLITBASE = SPLITBASE + 7
            SELECT PLAYERNSPLIT(PLAYERNO) 
                CASE 0,1,2,4
                    HANDNUMBER = 2
                ENDCASE
                CASE 3
                    IF HANDNUMBER = 0 
                        HANDNUMBER = 1
                    ELSE
                        HANDNUMBER = 2
                    ENDIF
                ENDCASE
                CASE 5
                    HANDNUMBER = HANDNUMBER + 1
                ENDCASE 
            ENDSELECT
        UNTIL HANDNUMBER >=2
        PLAYERNCASH(PLAYERNUMBER) = PLAYERNCASH(PLAYERNUMBER) + HANDREWARD(0) + HANDREWARD(1)
    NEXT PLAYERNUMBER
    // BLACKJACKFORM.COMMANDDEAL.VISIBLE = TRUE
    ROUNDSPLAYED = ROUNDSPLAYED + 1
ENDROC

PROC DOSPLITDEAL
    LOCAL USEIMAGE AS INTEGER
    LOCAL CARDSPACING AS INTEGER 
    CARDSPACING = 14
    IF PLAYERNSPLIT(PLAYERNO) = 1
        FOR N = 7 TO 13
            PLAYERBJCARDVAL(PLAYERNO, N) = 0
            PLAYERPKCARDVAL(PLAYERNO, N) = 0
        NEXT N
        IF PLAYERNO >= 1 AND PLAYERNO <= 5
            G = DISPPLAYERLEFT + (PLAYERNO - 1) * DISPPLAYERSPACING + 78 + INT(DISPPLAYERSPACING * .11) 
            H = DISPPLAYERTOP + DISPPLAYERVERTICAL * 0 
            PLAYERBJCARDVAL(PLAYERNO, 7) = PLAYERBJCARDVAL(PLAYERNO, 1)        
            PLAYERPKCARDVAL(PLAYERNO, 7) = PKCARDVALUE(CARDORDER(CARDNO))
            FOR N = 1 TO 6 
                PLAYERBJCARDVAL(PLAYERNO, N) = 0
                PLAYERPKCARDVAL(PLAYERNO, N) = 0
            NEXT N
            PLAYERNDRAWN(PLAYERNO) = 1
            N = PLAYERNSPLITCARD(PLAYERNO)
            SPRITE N+1, G, H, CARDIMAGE(N)        
            G = DISPPLAYERLEFT + (PLAYERNO - 1) * DISPPLAYERSPACING + 10 + CARDSPACING * 1
            H = DISPPLAYERTOP + DISPPLAYERVERTICAL * 0 + 12 * 1
            USEIMAGE = CARDIMAGE(CARDORDER(CARDNO))
            ANIMATEHIT(CARDORDER(CARDNO), G, H, USEIMAGE)
            NEWCARDVALUE = BJCARDVALUE(CARDORDER(CARDNO))
            PLAYERBJCARDVAL(PLAYERNO, 1) = BJCARDVALUE(CARDORDER(CARDNO))
            PLAYERSUCARDVAL(PLAYERNO, 1) = CARDSUITVALUE(CARDORDER(CARDNO))                
            CARDNO = CARDNO + 1
            PLAYERNDRAWN(PLAYERNO) = 2
            PLAYERNSPLIT(PLAYERNO) = 2        
            EXEC CALCTOTAL
            G = DISPPLAYERLEFT + (PLAYERNO - 1) * DISPPLAYERSPACING + 78 + INT(DISPPLAYERSPACING * .11) + CARDSPACING * 1
            H = DISPPLAYERTOP + DISPPLAYERVERTICAL * 0 + 12 * 1
            USEIMAGE = CARDIMAGE(CARDORDER(CARDNO))
            ANIMATEHIT(CARDORDER(CARDNO), G, H, USEIMAGE)
            PLAYERBJCARDVAL(PLAYERNO, 8) = BJCARDVALUE(CARDORDER(CARDNO))
            PLAYERSUCARDVAL(PLAYERNO, 8) = CARDSUITVALUE(CARDORDER(CARDNO))                
            CARDNO = CARDNO + 1        
            PLAYERNSPLIT(PLAYERNO) = 3
            PLAYERNDRAWN(PLAYERNO) = 9
            EXEC CALCTOTAL
            PLAYERNMESSAGE$(PLAYERNO) = STR$(PLAYERNTOTAL(PLAYERNO,0)) + "|T:" + STR$(PLAYERNTOTAL(PLAYERNO,1))
        ENDIF
        PLAYERNSPLIT(PLAYERNO) = 2
        PLAYERNDRAWN(PLAYERNO) = 2
        SHOWSTATS
     ELSE
      IF PLAYERNSPLIT(PLAYERNO) = 2 OR PLAYERNSPLIT(PLAYERNO) = 3
            FOR N = 14 TO 20
                PLAYERBJCARDVAL(PLAYERNO, N) = 0
            NEXT N
            G = DISPPLAYERLEFT + (PLAYERNO - 1) * DISPPLAYERSPACING + 148 + INT(DISPPLAYERSPACING * .17) 
            H = DISPPLAYERTOP + DISPPLAYERVERTICAL * 0 
            IF PLAYERNSPLIT(PLAYERNO) = 2
                PLAYERBJCARDVAL(PLAYERNO, 7) = PLAYERBJCARDVAL(PLAYERNO, 1)        
                FOR N = 1 TO 6 
                    PLAYERBJCARDVAL(PLAYERNO, N) = 0
                NEXT N
                PLAYERNDRAWN(PLAYERNO) = 1
            ENDIF     
            IF PLAYERNSPLIT(PLAYERNO) = 3
                PLAYERBJCARDVAL(PLAYERNO, 14) = PLAYERBJCARDVAL(PLAYERNO, 8)        
                FOR N = 8 TO 13
                    PLAYERBJCARDVAL(PLAYERNO, N) = 0
                NEXT N
                PLAYERNDRAWN(PLAYERNO) = 8
            ENDIF   
      ENDIF
     ENDIF
ENDROC

PROC DONEXTHAND    
    IF PLAYERNSPLIT(PLAYERNO) = 2 
        PLAYERNSPLIT(PLAYERNO) = 3
        PLAYERNDRAWN(PLAYERNO) = 9
    ENDIF
    IF PLAYERNSPLIT(PLAYERNO) = 3 AND PLAYERBJCARDVAL(PLAYERNO, 14) > 0
        PLAYERNSPLIT(PLAYERNO) = 4
        PLAYERNDRAWN(PLAYERNO) = 15
    ENDIF
    EXEC CALCTOTAL
ENDROC

PROC GETBETS    
    LOCAL PN AS INTEGER
    LOCAL DN AS INTEGER
    LOCAL N AS INTEGER
    LOCAL BETIN AS STRING
    LOCAL BETOK AS BOOLEAN
    LOCAL BETVAL AS FLOAT
    LOCAL ERRORMESSAGE AS STRING
    LOCAL QUITBOXLEFT AS INTEGER 
    LOCAL MX AS INTEGER
    LOCAL MY AS INTEGER
    QUITBOXLEFT = SELECTED_RES_X - 120
    CLS
    SET TEXT TRANSPARENT
    SYNC ON    
    FOR PN = 1 TO LASTPLAYER        
        CLEAR ENTRY BUFFER        
        SET TEXT FONT "TIMES NEW ROMAN"
        SET TEXT SIZE 20
        ERRORMESSAGE = ""
        REPEAT
            BETOK = FALSE            
            SYNC
            MX=MOUSEX
            MY=MOUSEY
            FOR DN = 1 TO LASTPLAYER
                INK RGB(240,160,40),RGB(0,0,0)
                CENTER TEXT DISPPLAYERLEFT+84+DISPPLAYERSPACING*(DN-1), DISPPLAYERTOP + DISPPLAYERVERTICAL * 6,  "PLAYER : " + STR$(DN)
                CENTER TEXT DISPPLAYERLEFT+84+DISPPLAYERSPACING*(DN-1), DISPPLAYERTOP + DISPPLAYERVERTICAL * 7,  "CASH : " + STR$(PLAYERNCASH(DN))                
                IF PN <> DN                 
                    TEXT DISPPLAYERLEFT+12+DISPPLAYERSPACING*(DN-1),DISPPLAYERTOP + DISPPLAYERVERTICAL * 8, "BET : " + STR$(PLAYERNBET(DN))
                ENDIF
            NEXT DN            
            BOX QUITBOXLEFT + 2 , 6, QUITBOXLEFT + 62 , 31, RGB(200,250,150), RGB(200,250,150), RGB(200,250,150), RGB(200,250,150)
            BOX QUITBOXLEFT + 3 , 7, QUITBOXLEFT + 61 , 20, RGB(0,0,32), RGB(0,0,192), RGB(0,0,32), RGB(0,0,192)    
            BOX QUITBOXLEFT + 3 , 20, QUITBOXLEFT + 61 , 30, RGB(0,0,192), RGB(0,0,32), RGB(0,0,192), RGB(0,0,32)            
            INK RGB(240,180,120),RGB(0,0,0)
            SET TEXT SIZE 20
            CENTER TEXT QUITBOXLEFT + 40 ,8 , "UIT"
            INK RGB(255,240,255),RGB(0,0,0)
            SET TEXT SIZE 26
            CENTER TEXT QUITBOXLEFT + 22 ,4, "Q" 
            BOX DISPPLAYERLEFT+54+DISPPLAYERSPACING*(PN-1),DISPPLAYERTOP + DISPPLAYERVERTICAL * 8,DISPPLAYERLEFT+131+DISPPLAYERSPACING*(PN-1),DISPPLAYERTOP + DISPPLAYERVERTICAL * 8 + 22,RGB(255,128,255),RGB(255,128,255),RGB(255,128,255),RGB(255,128,255)
            BOX DISPPLAYERLEFT+55+DISPPLAYERSPACING*(PN-1),DISPPLAYERTOP + DISPPLAYERVERTICAL * 8+1,DISPPLAYERLEFT+130+DISPPLAYERSPACING*(PN-1),DISPPLAYERTOP + DISPPLAYERVERTICAL * 8 + 21,RGB(0,64,0),RGB(0,0,0),RGB(0,64,0),RGB(0,0,0)            
            SET CURSOR DISPPLAYERLEFT+50+DISPPLAYERSPACING*(PN-1),DISPPLAYERTOP + DISPPLAYERVERTICAL * 10
            BETIN = ""
            FOR N=1 TO LEN(ENTRY$(1))
                IF MID$(ENTRY$(1),N,1) <> CHR$(13) 
                    BETIN = BETIN + MID$(ENTRY$(1),N)
                ENDIF
            NEXT N            
            IF MX >= QUITBOXLEFT AND MX<= QUITBOXLEFT + 62 AND MY >=2 AND MY <=31 AND MOUSECLICK = 1 THEN BETIN = "Q"
            BETVAL = VAL(BETIN)
            INK RGB(255,224,192),RGB(0,0,0)
            SET TEXT SIZE 20
            IF BETVAL > 9 AND BETVAL<1001 
                BETOK = TRUE
                ERRORMESSAGE = ""
                PLAYERNBET(PN) = BETVAL
                INK RGB(255,224,192),RGB(0,0,0)                
            ELSE                
                IF LEN(BETIN) > 1                  
                  IF BETVAL>1000 THEN ERRORMESSAGE = "The Maximum Bet is 1000."
                ENDIF
                IF BETIN <>"" AND BETVAL=0 AND UPPER$(BETIN) <> "Q" THEN ERRORMESSAGE = "You Must Enter a Number."                 
                IF UPPER$(BETIN) = "Q" THEN ERRORMESSAGE = "Quit? Press Enter to Confirm."
                IF INKEY$=CHR$(13) OR (MOUSECLICK = 1 AND UPPER$(BETIN) = "Q")
                    IF UPPER$(BETIN) = "Q" THEN EXITGAME = TRUE                    
                    IF (LEN(BETIN) =0 OR BETVAL = 0) THEN ERRORMESSAGE = "Nothing Entered."
                    IF BETVAL>0 AND BETVAL<10 THEN ERRORMESSAGE = "The Minimal Bet is 10."
                ENDIF                
                IF ERRORMESSAGE <> "" 
                    BETOK = FALSE
                    INK RGB(255,64,64),RGB(0,0,0)
                    CENTER TEXT DISPPLAYERLEFT+96+DISPPLAYERSPACING*(PN-1), DISPPLAYERTOP + DISPPLAYERVERTICAL * 9,  ERRORMESSAGE 
                    SET CURSOR 20,500
                ELSE
                    INK RGB(255,224,192),RGB(0,0,0)
                ENDIF
            ENDIF            
            TEXT DISPPLAYERLEFT+62+DISPPLAYERSPACING*(PN-1),DISPPLAYERTOP + DISPPLAYERVERTICAL * 8, ENTRY$(1)
            TEXT DISPPLAYERLEFT+12+DISPPLAYERSPACING*(PN-1),DISPPLAYERTOP + DISPPLAYERVERTICAL * 8, "BET"            
        UNTIL (INKEY$=CHR$(13) AND BETOK = TRUE) OR EXITGAME = TRUE
        REPEAT
        UNTIL INKEY$<>CHR$(13) 
    NEXT PN
    SYNC OFF
ENDROC

PROC SHOWSTATS
    LOCAL DN AS INTEGER
    LOCAL DISPDEALERLEFT AS INTEGER
    SET TEXT FONT "TIMES NEW ROMAN"
    SET TEXT SIZE 20
    SET TEXT TRANSPARENT
    DISPDEALERLEFT = INT(SELECTED_RES_X * .38) - 64
    // TEXT 2, 2,  "CARDNO : " + STR$(CARDNO) + " / " + STR$(TOTALCARDS)
    FOR DN = 0 TO LASTPLAYER        
        IF DN = 0 
            INK RGB(240,160,40),RGB(0,0,0)
            CENTER TEXT DISPDEALERLEFT, 16,  "DEALER"
            CENTER TEXT DISPDEALERLEFT, 17 + DISPPLAYERVERTICAL, PLAYERNMESSAGE$(DN)            
        ELSE
            INK RGB(240,160,40),RGB(0,0,0)
            CENTER TEXT DISPPLAYERLEFT+84+DISPPLAYERSPACING*(DN-1), DISPPLAYERTOP + DISPPLAYERVERTICAL * 6,  "PLAYER : " + STR$(DN)
            CENTER TEXT DISPPLAYERLEFT+84+DISPPLAYERSPACING*(DN-1), DISPPLAYERTOP + DISPPLAYERVERTICAL * 7,  "CASH : " + STR$(PLAYERNCASH(DN))
            CENTER TEXT DISPPLAYERLEFT+78+DISPPLAYERSPACING*(DN-1),DISPPLAYERTOP + DISPPLAYERVERTICAL * 8, "BET : " + STR$(PLAYERNBET(DN))
            IF LEN(PLAYERNMESSAGE$(DN)) < 22
                CENTER TEXT DISPPLAYERLEFT+78+DISPPLAYERSPACING*(DN-1),DISPPLAYERTOP + DISPPLAYERVERTICAL * 9, PLAYERNMESSAGE$(DN)
            ELSE
                TEXT DISPPLAYERLEFT+DISPPLAYERSPACING*(DN-1) - DISPPLAYERLEFT + 2,DISPPLAYERTOP + DISPPLAYERVERTICAL * 9, PLAYERNMESSAGE$(DN)
            ENDIF
        ENDIF
    NEXT DN
ENDROC

PROC SHOWCOMMANDS    
    LOCAL SPLITEXTRALEFT AS INTEGER
    LOCAL DN AS INTEGER
    IF PLAYERNSPLIT(PLAYERNO) = 3 OR PLAYERNSPLIT(PLAYERNO) = 4 
        SPLITEXTRALEFT = 16
    ELSE
        SPLITEXTRALEFT = 0
    ENDIF
    DN = PLAYERNO - 1    
    BOX DISPPLAYERLEFT + SPLITEXTRALEFT  - 2 + DISPPLAYERSPACING * DN, DISPPLAYERTOP + DISPPLAYERVERTICAL * 10 - 8, DISPPLAYERLEFT + SPLITEXTRALEFT  + 225 + DISPPLAYERSPACING * DN, DISPPLAYERTOP + DISPPLAYERVERTICAL * 12 + 26, RGB(128,32,128), RGB(32,192,64), RGB(32,192,64), RGB(128,32,128)
    BOX DISPPLAYERLEFT + SPLITEXTRALEFT  + 0 + DISPPLAYERSPACING * DN, DISPPLAYERTOP + DISPPLAYERVERTICAL * 10 - 6, DISPPLAYERLEFT + SPLITEXTRALEFT  + 223 + DISPPLAYERSPACING * DN, DISPPLAYERTOP + DISPPLAYERVERTICAL * 12 + 24, RGB(64,0,64), RGB(0,32,0), RGB(0,32,0), RGB(64,0,64)
    BOX DISPPLAYERLEFT + SPLITEXTRALEFT  + 4 + DISPPLAYERSPACING * DN, DISPPLAYERTOP + DISPPLAYERVERTICAL * 10 - 2, DISPPLAYERLEFT + SPLITEXTRALEFT  + 106 + DISPPLAYERSPACING * DN, DISPPLAYERTOP + DISPPLAYERVERTICAL * 10 + 21, RGB(200,250,150), RGB(200,250,150), RGB(200,250,150), RGB(200,250,150)
    BOX DISPPLAYERLEFT + SPLITEXTRALEFT  + 5 + DISPPLAYERSPACING * DN, DISPPLAYERTOP + DISPPLAYERVERTICAL * 10 - 1, DISPPLAYERLEFT + SPLITEXTRALEFT  + 105 + DISPPLAYERSPACING * DN, DISPPLAYERTOP + DISPPLAYERVERTICAL * 10 + 10, RGB(0,0,32), RGB(0,0,192), RGB(0,0,32), RGB(0,0,192)
    BOX DISPPLAYERLEFT + SPLITEXTRALEFT  + 5 + DISPPLAYERSPACING * DN, DISPPLAYERTOP + DISPPLAYERVERTICAL * 10 + 10, DISPPLAYERLEFT + SPLITEXTRALEFT  + 105 + DISPPLAYERSPACING * DN, DISPPLAYERTOP + DISPPLAYERVERTICAL * 10 + 20, RGB(0,0,192), RGB(0,0,32), RGB(0,0,192), RGB(0,0,32)
    SET TEXT SIZE 20
    INK RGB(240,180,120),RGB(0,0,0)
    CENTER TEXT DISPPLAYERLEFT + SPLITEXTRALEFT  + 68 + DISPPLAYERSPACING * DN, DISPPLAYERTOP + DISPPLAYERVERTICAL * 10, "IT"
    SET TEXT SIZE 28
    INK RGB(255,240,255),RGB(0,0,0)    
    CENTER TEXT DISPPLAYERLEFT + SPLITEXTRALEFT  + 48 + DISPPLAYERSPACING * DN, DISPPLAYERTOP + DISPPLAYERVERTICAL * 10 - 3, "H"
    BOX DISPPLAYERLEFT + SPLITEXTRALEFT  + 117 + DISPPLAYERSPACING * DN, DISPPLAYERTOP + DISPPLAYERVERTICAL * 10 - 2, DISPPLAYERLEFT + SPLITEXTRALEFT  + 218 + DISPPLAYERSPACING * DN, DISPPLAYERTOP + DISPPLAYERVERTICAL * 10 + 21, RGB(200,250,150), RGB(200,250,150), RGB(200,250,150), RGB(200,250,150)
    BOX DISPPLAYERLEFT + SPLITEXTRALEFT  + 118 + DISPPLAYERSPACING * DN, DISPPLAYERTOP + DISPPLAYERVERTICAL * 10 - 1, DISPPLAYERLEFT + SPLITEXTRALEFT  + 217 + DISPPLAYERSPACING * DN, DISPPLAYERTOP + DISPPLAYERVERTICAL * 10 + 10, RGB(0,0,32), RGB(0,0,192), RGB(0,0,32), RGB(0,0,192)
    BOX DISPPLAYERLEFT + SPLITEXTRALEFT  + 118 + DISPPLAYERSPACING * DN, DISPPLAYERTOP + DISPPLAYERVERTICAL * 10 + 10, DISPPLAYERLEFT + SPLITEXTRALEFT  + 217 + DISPPLAYERSPACING * DN, DISPPLAYERTOP + DISPPLAYERVERTICAL * 10 + 20, RGB(0,0,192), RGB(0,0,32), RGB(0,0,192), RGB(0,0,32)
    INK RGB(240,180,120),RGB(0,0,0)
    SET TEXT SIZE 20
    CENTER TEXT DISPPLAYERLEFT + SPLITEXTRALEFT  + 180 + DISPPLAYERSPACING * DN,DISPPLAYERTOP + DISPPLAYERVERTICAL * 10, "TAND"
    INK RGB(255,240,255),RGB(0,0,0)
    SET TEXT SIZE 28
    CENTER TEXT DISPPLAYERLEFT + SPLITEXTRALEFT  + 149 + DISPPLAYERSPACING * DN,DISPPLAYERTOP + DISPPLAYERVERTICAL * 10 - 4, "S"
    IF PLAYERNDOUBLEUSED(PLAYERNO) = 0 
        BOX DISPPLAYERLEFT + SPLITEXTRALEFT  + 4 + DISPPLAYERSPACING * DN, DISPPLAYERTOP + DISPPLAYERVERTICAL * 11 - 2, DISPPLAYERLEFT + SPLITEXTRALEFT  + 106 + DISPPLAYERSPACING * DN, DISPPLAYERTOP + DISPPLAYERVERTICAL * 11 + 21, RGB(200,250,150), RGB(200,250,150), RGB(200,250,150), RGB(200,250,150)
        BOX DISPPLAYERLEFT + SPLITEXTRALEFT  + 5 + DISPPLAYERSPACING * DN, DISPPLAYERTOP + DISPPLAYERVERTICAL * 11 - 1, DISPPLAYERLEFT + SPLITEXTRALEFT  + 105 + DISPPLAYERSPACING * DN, DISPPLAYERTOP + DISPPLAYERVERTICAL * 11 + 10, RGB(0,0,32), RGB(0,0,192), RGB(0,0,32), RGB(0,0,192)        
        BOX DISPPLAYERLEFT + SPLITEXTRALEFT  + 5 + DISPPLAYERSPACING * DN, DISPPLAYERTOP + DISPPLAYERVERTICAL * 11 + 10, DISPPLAYERLEFT + SPLITEXTRALEFT  + 105 + DISPPLAYERSPACING * DN, DISPPLAYERTOP + DISPPLAYERVERTICAL * 11 + 20, RGB(0,0,192), RGB(0,0,32), RGB(0,0,192), RGB(0,0,32)        
        INK RGB(240,180,120),RGB(0,0,0)
        SET TEXT SIZE 20
        CENTER TEXT DISPPLAYERLEFT + SPLITEXTRALEFT  + 64 + DISPPLAYERSPACING * DN,DISPPLAYERTOP + DISPPLAYERVERTICAL * 11, "OUBLE"
        INK RGB(255,240,255),RGB(0,0,0)
        SET TEXT SIZE 28
        CENTER TEXT DISPPLAYERLEFT + SPLITEXTRALEFT  + 24 + DISPPLAYERSPACING * DN,DISPPLAYERTOP + DISPPLAYERVERTICAL * 11 - 4, "D"
    ENDIF    
    IF PLAYERNSPLIT(PLAYERNO) = 1 AND PLAYERNDRAWN(PLAYERNO) <= 2
        BOX DISPPLAYERLEFT + SPLITEXTRALEFT  + 117 + DISPPLAYERSPACING * DN, DISPPLAYERTOP + DISPPLAYERVERTICAL * 11 - 2, DISPPLAYERLEFT + SPLITEXTRALEFT  + 218 + DISPPLAYERSPACING * DN, DISPPLAYERTOP + DISPPLAYERVERTICAL * 11 + 21, RGB(200,250,150), RGB(200,250,150), RGB(200,250,150), RGB(200,250,150)
        BOX DISPPLAYERLEFT + SPLITEXTRALEFT  + 118 + DISPPLAYERSPACING * DN, DISPPLAYERTOP + DISPPLAYERVERTICAL * 11 - 1, DISPPLAYERLEFT + SPLITEXTRALEFT  + 217 + DISPPLAYERSPACING * DN, DISPPLAYERTOP + DISPPLAYERVERTICAL * 11 + 10, RGB(0,0,32), RGB(0,0,192), RGB(0,0,32), RGB(0,0,192)    
        BOX DISPPLAYERLEFT + SPLITEXTRALEFT  + 118 + DISPPLAYERSPACING * DN, DISPPLAYERTOP + DISPPLAYERVERTICAL * 11 + 10, DISPPLAYERLEFT + SPLITEXTRALEFT  + 217 + DISPPLAYERSPACING * DN, DISPPLAYERTOP + DISPPLAYERVERTICAL * 11 + 20, RGB(0,0,192), RGB(0,0,32), RGB(0,0,192), RGB(0,0,32)        
        INK RGB(240,180,120),RGB(0,0,0)
        SET TEXT SIZE 20
        CENTER TEXT DISPPLAYERLEFT + SPLITEXTRALEFT  + 162 + DISPPLAYERSPACING * DN,DISPPLAYERTOP + DISPPLAYERVERTICAL * 11, "SPLI"
        INK RGB(255,240,255),RGB(0,0,0)
        SET TEXT SIZE 28
        CENTER TEXT DISPPLAYERLEFT + SPLITEXTRALEFT  + 190 + DISPPLAYERSPACING * DN,DISPPLAYERTOP + DISPPLAYERVERTICAL * 11 - 4, "T"
    ENDIF    
    IF ALLOWSURRENDER = TRUE AND PLAYERNDRAWN(PLAYERNO) = 2 AND PLAYERNSPLIT(PLAYERNO) <= 1
        BOX DISPPLAYERLEFT + SPLITEXTRALEFT  + 4 + DISPPLAYERSPACING * DN, DISPPLAYERTOP + DISPPLAYERVERTICAL * 12 - 2, DISPPLAYERLEFT + SPLITEXTRALEFT  + 140 + DISPPLAYERSPACING * DN, DISPPLAYERTOP + DISPPLAYERVERTICAL * 12 + 21, RGB(200,250,150), RGB(200,250,150), RGB(200,250,150), RGB(200,250,150)
        BOX DISPPLAYERLEFT + SPLITEXTRALEFT  + 5 + DISPPLAYERSPACING * DN, DISPPLAYERTOP + DISPPLAYERVERTICAL * 12 - 1, DISPPLAYERLEFT + SPLITEXTRALEFT  + 139 + DISPPLAYERSPACING * DN, DISPPLAYERTOP + DISPPLAYERVERTICAL * 12 + 10, RGB(0,0,32), RGB(0,0,192), RGB(0,0,32), RGB(0,0,192)    
        BOX DISPPLAYERLEFT + SPLITEXTRALEFT  + 5 + DISPPLAYERSPACING * DN, DISPPLAYERTOP + DISPPLAYERVERTICAL * 12 + 10, DISPPLAYERLEFT + SPLITEXTRALEFT  + 139 + DISPPLAYERSPACING * DN, DISPPLAYERTOP + DISPPLAYERVERTICAL * 12 + 20, RGB(0,0,192), RGB(0,0,32), RGB(0,0,192), RGB(0,0,32)        
        INK RGB(240,180,120),RGB(0,0,0)
        SET TEXT SIZE 20
        CENTER TEXT DISPPLAYERLEFT + SPLITEXTRALEFT  + 72 + DISPPLAYERSPACING * DN,DISPPLAYERTOP + DISPPLAYERVERTICAL * 12, "S   RRENDER"
        INK RGB(255,240,255),RGB(0,0,0)
        SET TEXT SIZE 28
        CENTER TEXT DISPPLAYERLEFT + SPLITEXTRALEFT  + 35 + DISPPLAYERSPACING * DN,DISPPLAYERTOP + DISPPLAYERVERTICAL * 12 - 4, "U"        
    ENDIF
    IF PLAYERNSPLIT(PLAYERNO) = 2 
        BOX DISPPLAYERLEFT + SPLITEXTRALEFT  + 143 + DISPPLAYERSPACING * DN, DISPPLAYERTOP + DISPPLAYERVERTICAL * 12 - 2, DISPPLAYERLEFT + SPLITEXTRALEFT  + 213 + DISPPLAYERSPACING * DN, DISPPLAYERTOP + DISPPLAYERVERTICAL * 12 + 21, RGB(10,140,140), RGB(100,10,10), RGB(100,10,10), RGB(20,140,140)
        INK RGB(255,127,191),RGB(0,0,0)
        SET TEXT SIZE 22        
        CENTER TEXT DISPPLAYERLEFT + SPLITEXTRALEFT  + 180 + DISPPLAYERSPACING * DN,DISPPLAYERTOP + DISPPLAYERVERTICAL * 12, "HAND 1"
    ENDIF        
    IF PLAYERNSPLIT(PLAYERNO) = 3
        BOX DISPPLAYERLEFT + SPLITEXTRALEFT  + 143 + DISPPLAYERSPACING * DN, DISPPLAYERTOP + DISPPLAYERVERTICAL * 12 - 2, DISPPLAYERLEFT + SPLITEXTRALEFT  + 213 + DISPPLAYERSPACING * DN, DISPPLAYERTOP + DISPPLAYERVERTICAL * 12 + 21, RGB(10,140,140), RGB(100,10,10), RGB(100,10,10), RGB(20,140,140)
        INK RGB(255,127,191),RGB(0,0,0)
        SET TEXT SIZE 22
        CENTER TEXT DISPPLAYERLEFT + SPLITEXTRALEFT  + 180 + DISPPLAYERSPACING * DN,DISPPLAYERTOP + DISPPLAYERVERTICAL * 12, "HAND 2"    
    ENDIF        
    IF PLAYERNSPLIT(PLAYERNO) = 4
        BOX DISPPLAYERLEFT + SPLITEXTRALEFT  + 143 + DISPPLAYERSPACING * DN, DISPPLAYERTOP + DISPPLAYERVERTICAL * 12 - 2, DISPPLAYERLEFT + SPLITEXTRALEFT  + 213 + DISPPLAYERSPACING * DN, DISPPLAYERTOP + DISPPLAYERVERTICAL * 12 + 21, RGB(10,140,140), RGB(100,10,10), RGB(100,10,10), RGB(20,140,140)
        INK RGB(255,127,191),RGB(0,0,0)
        SET TEXT SIZE 22
        CENTER TEXT DISPPLAYERLEFT + SPLITEXTRALEFT  + 180 + DISPPLAYERSPACING * DN,DISPPLAYERTOP + DISPPLAYERVERTICAL * 12, "HAND 3"    
    ENDIF        
ENDROC

PROC SHUFFLEDECKS
    LOCAL B AS INTEGER
    LOCAL I AS INTEGER
    LOCAL J AS INTEGER
    LOCAL K AS INTEGER
    LOCAL L AS INTEGER
    LOCAL N AS INTEGER
    LOCAL M AS INTEGER
    LOCAL O AS INTEGER
    LOCAL F AS FLOAT
    LOCAL H AS INTEGER
    LOCAL G0 AS INTEGER
    LOCAL G1 AS INTEGER
    LOCAL G2 AS INTEGER
    LOCAL D$ AS STRING
    DIM OLDORDER(512) AS INTEGER
    SYNC OFF
    D$ = MID$(GET DATE$,5) + MID$(GET DATE$,4) + MID$(GET DATE$, 2) + MID$(GET DATE$,8) 
    J = VAL(D$)
    SYNC OFF
    G1 = SELECTED_RES_Y * .2 + 24
    F = (SELECTED_RES_X * 0.6) / TOTALCARDS
    FOR I = 0 TO TOTALCARDS + JOKERSPRESANT
        CARDORDER(I) = -1
        SPRITE I+1, SELECTED_RES_X * .18 + F * I  , G1 , CARDBACKIMAGE
    NEXT I
    RANDOMIZE -TIMER + J
    REPEAT
        J = 5 + INT(RND(3)* 2)
    UNTIL (TOTALCARDS MOD J) > 0 AND ((TOTALCARDS + 1) MOD J) <> 2 AND ((TOTALCARDS + 1) MOD J) <> 3 AND ((TOTALCARDS + 1) MOD J) <> 4
    CARDNO = 0
    FOR I = 0 TO TOTALCARDS + JOKERSPRESANT
        IF CARDORDER(I) = -1 
            CARDORDER(I) = CARDNO 
            CARDNO = (CARDNO + J) MOD (TOTALCARDS + 1 + JOKERSPRESANT)
        ENDIF
    NEXT I
    CARDNO = 0
    M = 0
    FOR M = 0 TO NUMBER_OF_DECKS
        FOR I = 0 TO TOTALCARDS            
            J = INT(RND(TOTALCARDS))
            IF I = J THEN J = INT(RND(TOTALCARDS + JOKERSPRESANT))
            IF I = J THEN J = INT(RND(TOTALCARDS + JOKERSPRESANT))
            K = CARDORDER(J)
            CARDORDER(J) = CARDORDER(I)
            CARDORDER(I) = K            
        NEXT I
        IF M = 1 
            FOR I = 0 TO TOTALCARDS + JOKERSPRESANT
                OLDORDER(I) = CARDORDER(I)
            NEXT I    
        ENDIF
    NEXT M
    SELECT NUMBER_OF_DECKS
        CASE 3,4
            L = 4
        ENDCASE            
        CASE 5,6
            L = 7
        ENDCASE            
        CASE 7,8,9
            L = 10
        ENDCASE
    ENDSELECT
    G2 = SELECTED_RES_Y * .8 
    G1 = SELECTED_RES_Y * .6
    G0 = SELECTED_RES_Y * .4
    I = 0 
    REPEAT
        K = OLDORDER(I)
        J = CARDORDER(I)
        IF (I MOD L) = 1
            SPRITE K+1, SELECTED_RES_X * .36 + F * K * .5 , G0 , CARDBACKIMAGE
            SYNC
        ENDIF
        IF (I MOD L) = 2
            SPRITE K+1, SELECTED_RES_X * .36 + F * J * .5  , G1 , CARDBACKIMAGE
            SYNC
        ENDIF
        SPRITE K+1, SELECTED_RES_X * .18 + F * J  , G2 , CARDBACKIMAGE
        SET SPRITE PRIORITY K+1,J+1      
        I = I + 1
    UNTIL I > TOTALCARDS + JOKERSPRESANT
    CARDNO = 0
    FOR I = 0 TO  TOTALCARDS + JOKERSPRESANT
       SPRITE I+1, -200, -200, CARDIMAGE(I)
    NEXT I
ENDROC

PROC INIT_DEFAULTS
    CARDBACKIMAGE = 60
    LASTPLAYER = 1
    DECKSIZE = 52    
    NUMBER_OF_DECKS = 4
    DOUBLEDOWNSET = 0
    SPLITSET = 0
    BONUS777  = TRUE
    BONUS678  = FALSE
    DEALER17TIEWINS  = FALSE
    DEALERSOFT17HIT = FALSE
    CARDCHARLIEWINSET = 6
    SUIT21BONUS  = FALSE    
    COLOR21BONUS  = FALSE    
    DOUBLEDOWN3UP = FALSE           
    ALLOWSURRENDER = FALSE
ENDROC

PROC DOSETTINGS    
   DIM DISPMODES$(128) AS STRING         
   LOCAL A AS INTEGER
   LOCAL B AS INTEGER
   LOCAL C AS INTEGER
   LOCAL I AS INTEGER
   LOCAL J AS INTEGER
   LOCAL K AS INTEGER   
   LOCAL L AS INTEGER   
   LOCAL N AS INTEGER   
   LOCAL BUTTONUP AS BOOLEAN
   LOCAL SELECTED_MODE AS INTEGER
   LOCAL MX AS INTEGER
   LOCAL MY AS INTEGER
   SET WINDOW OFF
   SET DISPLAY MODE 1024,768,32
   SELECTED_BITDEPTH=32
   EMPTY CHECKLIST
   PERFORM CHECKLIST FOR DISPLAY MODES
    A = 1
    N = 1
    B = CHECKLIST VALUE C(1)
    
    REPEAT 
        IF CHECKLIST VALUE C(N) = B AND CHECKLIST VALUE A(N)>799
            MODE_RES_X(A) = CHECKLIST VALUE A(N)
            MODE_RES_Y(A) = CHECKLIST VALUE B(N)        
            IF MODE_RES_X(A) = 800 AND MODE_RES_Y(A) = 600 AND SELECTED_MODE <=1
                SELECTED_MODE = A
                SELECTED_RES_X = MODE_RES_X(A)
                SELECTED_RES_Y = MODE_RES_Y(A)
            ENDIF            
            A = A + 1
        ENDIF
        N = N + 1
    UNTIL CHECKLIST VALUE C(N) <> B OR N >= CHECKLIST QUANTITY 
    POSSIBLE_MODES = A 
    A = 1
    B = CHECKLIST VALUE C(1)
    MODE_BITDEPTH(1) = B
    FOR N=1 TO CHECKLIST QUANTITY 
        IF CHECKLIST VALUE C(N) <> B 
            A = A + 1    
            B = CHECKLIST VALUE C(N)
            MODE_BITDEPTH(A) = B
        ENDIF
    NEXT N
//   SET WINDOW ON
   REPEAT
      RESET_TITLE = 0
      CLS   
      CENTER TEXT 512,82, "ATARI 8-BIT BLACKJACK "
      INK RGB(120,64,240),RGB(160,80,40)
      SET TEXT SIZE 20
      CENTER TEXT 512,128,"A Game By Peter J. Meyer"
      SET TEXT SIZE 18
      INK RGB(255,32,96),RGB(0,0,0)
      TEXT 2,128,"FINAL BETA"
      SET TEXT SIZE 16
      SET TEXT FONT "COURIER NEW"
      INK RGB(255,96,64),RGB(160,80,40)
      WATCHFORNOHOVER = 0
      SET CURSOR 10,200
      INK RGB(255,96,64),RGB(160,80,40)
      REPEAT
        IF MOUSECLICK=0 THEN BUTTONUP = TRUE        
         HOVERING = 0
         SELECTING = 0
         MX=MOUSEX
         MY=MOUSEY
         IF MX>10 AND MX<90 AND MY>680 AND MY<700
            HOVERING=1
            IF MOUSECLICK=1
               SELECTING = 1
               SHOW_MODES = 1
            ENDIF
         ENDIF
         IF MX>860 AND MX<940 AND MY>680 AND MY<700
            HOVERING=2
            IF MOUSECLICK=1 THEN SELECTING=2
         ENDIF
         IF MX>860 AND MX<940 AND MY>660 AND MY<680
            HOVERING=4
            IF MOUSECLICK=1
               SELECTING=3
               RESET_TITLE = 0
            ENDIF
         ENDIF
         IF MX>140 AND MX<260 AND MY>500 AND MY<520
             IF MOUSECLICK=1 
                DECKSIZE = 48
             ENDIF
         ENDIF
         IF MX>140 AND MX<260 AND MY>520 AND MY<540
             IF MOUSECLICK=1 
                DECKSIZE = 52
             ENDIF
         ENDIF
//         IF MX>140 AND MX<260 AND MY>540 AND MY<560
//             IF MOUSECLICK=1 
//                DECKSIZE = 56
//             ENDIF
//         ENDIF
         IF MX>140 AND MX<260 AND MY>640 AND MY<660
             IF MOUSECLICK=1 
                NUMBER_OF_DECKS = 4
             ENDIF
         ENDIF
         IF MX>140 AND MX<260 AND MY>660 AND MY<680
             IF MOUSECLICK=1 
                NUMBER_OF_DECKS = 6
             ENDIF
         ENDIF
         IF MX>140 AND MX<260 AND MY>680 AND MY<700
             IF MOUSECLICK=1 
                NUMBER_OF_DECKS = 8
             ENDIF
         ENDIF
        J = 540
        IF MX>290 AND MX<560 AND MY > J AND MY < J+20
             IF MOUSECLICK=1 AND BUTTONUP = TRUE
                BUTTONUP = FALSE
                BONUS777 = 1 - BONUS777 
             ENDIF
         ENDIF
         J = J + 20
         IF MX>290 AND MX<560 AND MY > J AND MY < J+20
             IF MOUSECLICK=1  AND BUTTONUP = TRUE
                BUTTONUP = FALSE
                BONUS678 = 1 - BONUS678                
             ENDIF
         ENDIF
         J = J + 20
         IF MX>290 AND MX<560 AND MY > J AND MY < J+20
             IF MOUSECLICK=1  AND BUTTONUP = TRUE
                BUTTONUP = FALSE
                DEALER17TIEWINS = 1 - DEALER17TIEWINS
             ENDIF
         ENDIF
         J = J + 20
         IF MX>290 AND MX<560 AND MY > J AND MY < J+20
             IF MOUSECLICK=1  AND BUTTONUP = TRUE
                BUTTONUP = FALSE
                DEALERSOFT17HIT = 1 - DEALERSOFT17HIT
             ENDIF
         ENDIF
         J = J + 20
        IF MX>290 AND MX<560 AND MY > J AND MY < J+20
             IF MOUSECLICK=1  AND BUTTONUP = TRUE
                BUTTONUP = FALSE
                IF CARDCHARLIEWINSET = 6 
                    CARDCHARLIEWINSET = 5
                ELSE
                    CARDCHARLIEWINSET = 6
                ENDIF
             ENDIF
         ENDIF    
         J = J + 20            
        IF MX>290 AND MX<560 AND MY > J AND MY < J+20
             IF MOUSECLICK=1  AND BUTTONUP = TRUE
                BUTTONUP = FALSE
                SUIT21BONUS = 1 - SUIT21BONUS
                COLOR21BONUS = FALSE
             ENDIF
         ENDIF    
         J = J + 20            
        IF MX>290 AND MX<560 AND MY > J AND MY < J+20
             IF MOUSECLICK=1  AND BUTTONUP = TRUE
                BUTTONUP = FALSE
                COLOR21BONUS = 1 - COLOR21BONUS
                SUIT21BONUS = FALSE
             ENDIF
         ENDIF    
         J = J + 20            
        IF MX>290 AND MX<560 AND MY > J AND MY < J+20
             IF MOUSECLICK=1 AND BUTTONUP = TRUE
                BUTTONUP = FALSE
                ALLOWSURRENDER = 1 - ALLOWSURRENDER
             ENDIF
         ENDIF                
        IF MX>600 AND MX<800 AND MY>500 AND MY<520
             IF MOUSECLICK = 1
                DOUBLEDOWNSET = 0
             ENDIF
         ENDIF
         IF MX>600 AND MX<800 AND MY>520 AND MY<540
             IF MOUSECLICK = 1
                DOUBLEDOWNSET = 1
                DOUBLEDOWN3UP = FALSE
             ENDIF
         ENDIF
         IF MX>600 AND MX<800 AND MY>540 AND MY<560
             IF MOUSECLICK = 1
                DOUBLEDOWNSET = 2
                DOUBLEDOWN3UP = FALSE
             ENDIF
         ENDIF
         IF MX>600 AND MX<800 AND MY>560 AND MY<580
             IF MOUSECLICK = 1 AND BUTTONUP = TRUE AND DOUBLEDOWNSET = 0
                DOUBLEDOWN3UP = 1 - DOUBLEDOWN3UP
                BUTTONUP = FALSE
             ENDIF
         ENDIF
         IF SPLITSET >= 3 THEN SPLITSET = 0
         IF MX>600 AND MX<800 AND MY>640 AND MY<660
             IF MOUSECLICK = 1
                SPLITSET = 0
             ENDIF
         ENDIF
         IF MX>600 AND MX<800 AND MY>660 AND MY<680
             IF MOUSECLICK = 1
                SPLITSET = 1
             ENDIF
         ENDIF
         IF MX>600 AND MX<800 AND MY>680 AND MY<700
             IF MOUSECLICK = 1
                SPLITSET = 2
             ENDIF
         ENDIF

         IF MX>850 AND MX<950 AND MY>500 AND MY<520
             IF MOUSECLICK = 1
                LASTPLAYER = 1
             ENDIF
         ENDIF
         IF MX>850 AND MX<950 AND MY>520 AND MY<540
             IF MOUSECLICK = 1
                LASTPLAYER = 2
             ENDIF
         ENDIF
         IF MX>850 AND MX<950 AND MY>540 AND MY<560
             IF MOUSECLICK = 1
                LASTPLAYER = 3
             ENDIF
         ENDIF
         IF MX>850 AND MX<950 AND MY>560 AND MY<580 AND SELECTED_RES_X > 1111 
             IF MOUSECLICK = 1
                LASTPLAYER = 4
             ENDIF
         ENDIF

         IF SHOW_MODES = 1
            INK RGB(64,16,16),RGB(0,0,0)            
            BOX 2, 679-POSSIBLE_MODES * 20, 128, 701
            INK RGB(128,64,64),RGB(0,0,0)
            LINE 2, 679-POSSIBLE_MODES * 20, 128, 679-POSSIBLE_MODES * 20
            LINE 2, 679-POSSIBLE_MODES * 20, 2, 701
            LINE 128, 679-POSSIBLE_MODES * 20, 128, 701
            LINE 2, 701, 128, 701
            LINE 2, 660, 128, 660
            LINE 2, 680, 128, 680
            INK RGB(240,160,40),RGB(0,0,0)
            IF MX>5 AND MX<99 AND MY>659-POSSIBLE_MODES * 20  AND MY<660
               HOVERING = ((MY -(660 - POSSIBLE_MODES * 20)) / 20)
               IF MOUSECLICK=1
                  WATCHFORNOHOVER=1
                  SELECTED_MODE = HOVERING 
                  SELECTED_RES_X = MODE_RES_X(HOVERING)
                  SELECTED_RES_Y = MODE_RES_Y(HOVERING)
               ENDIF
            ENDIF
            IF MX>5 AND MX<99 AND MY>659 AND MY<680
               HOVERING=4
               IF MOUSECLICK=1
                  IF MX<=56
                     SELECTED_BITDEPTH=16
                  ELSE
                     SELECTED_BITDEPTH=32
                  ENDIF
                  SELECTING=7
                  WATCHFORNOHOVER=1
               ENDIF
            ENDIF
            FOR N = 1 TO POSSIBLE_MODES
                IF (HOVERING = 9 + N) OR (N = POSSIBLE_MODES AND HOVERING = 4) 

                ELSE

                ENDIF
                IF N < POSSIBLE_MODES
                    CENTER TEXT 66, 660 - POSSIBLE_MODES*20+N*20, "X"
                    CENTER TEXT 37, 660 - POSSIBLE_MODES*20+N*20, STR$(MODE_RES_X(N))
                    CENTER TEXT 93, 660 - POSSIBLE_MODES*20+N*20, STR$(MODE_RES_Y(N))
                ELSE
                    CENTER TEXT 35, 660,"16 BIT"
                    CENTER TEXT 93, 660,"32 BIT"    
                ENDIF
            NEXT N
            INK RGB(255,255,127),RGB(160,80,40)
            CENTER TEXT 65,660 - POSSIBLE_MODES*20 + 20 * SELECTED_MODE,"[           ]"
            CENTER TEXT -23 + 3.6 * SELECTED_BITDEPTH,660,"[      ]"
            // CENTER TEXT 108,360,"640 X 480"
            // CENTER TEXT 108,380,"800 X 600"
            // CENTER TEXT 108,400,"1024 X 768"
         ELSE
            INK RGB(0,0,0),RGB(0,0,0)
            BOX 2, 679-POSSIBLE_MODES * 20, 120, 701            
         ENDIF
         IF DECKSIZE = 48 
            J = 498
         ENDIF
         IF DECKSIZE = 52
            J = 518
         ENDIF
//         IF DECKSIZE = 56
//            J = 538
//         ENDIF
         INK RGB(0,0,0),RGB(0,0,0)
         BOX 139,495,261,705
         BOX 278,495,561,705
         BOX 599,495,801,705
         BOX 839,495,961,605
         BOX 139,J,261,J+19,RGB(120,16,16),RGB(120,16,16),RGB(120,16,16),RGB(120,16,16)
         BOX 140,J+1,260,J+9,RGB(0,0,36),RGB(72,16,16),RGB(0,0,36),RGB(72,16,16)
         BOX 140,J+9,260,J+18,RGB(72,16,16),RGB(0,0,36),RGB(72,16,16),RGB(0,0,36)
         J = (NUMBER_OF_DECKS - 4) * 10 + 640
         BOX 139,J,261,J+19,RGB(120,16,16),RGB(120,16,16),RGB(120,16,16),RGB(120,16,16)
         BOX 140,J+1,260,J+9,RGB(0,0,36),RGB(72,16,16),RGB(0,0,36),RGB(72,16,16)
         BOX 140,J+9,260,J+18,RGB(72,16,16),RGB(0,0,36),RGB(72,16,16),RGB(0,0,36)
         J=538
         IF BONUS777 = TRUE             
             BOX 279,J,561,J+19,RGB(120,16,16),RGB(120,16,16),RGB(120,16,16),RGB(120,16,16)
             BOX 280,J+1,560,J+9,RGB(0,0,36),RGB(72,16,16),RGB(0,0,36),RGB(72,16,16)
             BOX 280,J+9,560,J+18,RGB(72,16,16),RGB(0,0,36),RGB(72,16,16),RGB(0,0,36)
         ENDIF
         J = J + 20
         IF BONUS678 = TRUE
             BOX 279,J,561,J+19,RGB(120,16,16),RGB(120,16,16),RGB(120,16,16),RGB(120,16,16)
             BOX 280,J+1,560,J+9,RGB(0,0,36),RGB(72,16,16),RGB(0,0,36),RGB(72,16,16)
             BOX 280,J+9,560,J+18,RGB(72,16,16),RGB(0,0,36),RGB(72,16,16),RGB(0,0,36)
         ENDIF
         J = J + 20
         IF DEALER17TIEWINS = TRUE
             J = 578
             BOX 279,J,561,J+19,RGB(120,16,16),RGB(120,16,16),RGB(120,16,16),RGB(120,16,16)
             BOX 280,J+1,560,J+9,RGB(0,0,36),RGB(72,16,16),RGB(0,0,36),RGB(72,16,16)
             BOX 280,J+9,560,J+18,RGB(72,16,16),RGB(0,0,36),RGB(72,16,16),RGB(0,0,36)
         ENDIF
         J = J + 20
         IF DEALERSOFT17HIT = TRUE
             BOX 279,J,561,J+19,RGB(120,16,16),RGB(120,16,16),RGB(120,16,16),RGB(120,16,16)
             BOX 280,J+1,560,J+9,RGB(0,0,36),RGB(72,16,16),RGB(0,0,36),RGB(72,16,16)
             BOX 280,J+9,560,J+18,RGB(72,16,16),RGB(0,0,36),RGB(72,16,16),RGB(0,0,36)
         ENDIF
         J = J + 20
         IF CARDCHARLIEWINSET = 5
             BOX 279,J,561,J+19,RGB(120,16,16),RGB(120,16,16),RGB(120,16,16),RGB(120,16,16)
             BOX 280,J+1,560,J+9,RGB(0,0,36),RGB(72,16,16),RGB(0,0,36),RGB(72,16,16)
             BOX 280,J+9,560,J+18,RGB(72,16,16),RGB(0,0,36),RGB(72,16,16),RGB(0,0,36)
         ENDIF
         J = J + 20
         IF SUIT21BONUS = TRUE
             BOX 279,J,561,J+19,RGB(120,16,16),RGB(120,16,16),RGB(120,16,16),RGB(120,16,16)
             BOX 280,J+1,560,J+9,RGB(0,0,36),RGB(72,16,16),RGB(0,0,36),RGB(72,16,16)
             BOX 280,J+9,560,J+18,RGB(72,16,16),RGB(0,0,36),RGB(72,16,16),RGB(0,0,36)
         ENDIF
         J = J + 20
         IF COLOR21BONUS = TRUE
             BOX 279,J,561,J+19,RGB(120,16,16),RGB(120,16,16),RGB(120,16,16),RGB(120,16,16)
             BOX 280,J+1,560,J+9,RGB(0,0,36),RGB(72,16,16),RGB(0,0,36),RGB(72,16,16)
             BOX 280,J+9,560,J+18,RGB(72,16,16),RGB(0,0,36),RGB(72,16,16),RGB(0,0,36)
         ENDIF
         J = J + 20
         IF ALLOWSURRENDER = TRUE
             BOX 279,J,561,J+19,RGB(120,16,16),RGB(120,16,16),RGB(120,16,16),RGB(120,16,16)
             BOX 280,J+1,560,J+9,RGB(0,0,36),RGB(72,16,16),RGB(0,0,36),RGB(72,16,16)
             BOX 280,J+9,560,J+18,RGB(72,16,16),RGB(0,0,36),RGB(72,16,16),RGB(0,0,36)
         ENDIF
         J = 558
         IF DOUBLEDOWN3UP = TRUE
             BOX 599,J,801,J+19,RGB(120,16,16),RGB(120,16,16),RGB(120,16,16),RGB(120,16,16)
             BOX 600,J+1,800,J+9,RGB(0,0,36),RGB(72,16,16),RGB(0,0,36),RGB(72,16,16)
             BOX 600,J+9,800,J+18,RGB(72,16,16),RGB(0,0,36),RGB(72,16,16),RGB(0,0,36)
         ENDIF
         J = 498 + DOUBLEDOWNSET * 20
         BOX 599,J,801,J+19,RGB(120,16,16),RGB(120,16,16),RGB(120,16,16),RGB(120,16,16)
         BOX 600,J+1,800,J+9,RGB(0,0,36),RGB(72,16,16),RGB(0,0,36),RGB(72,16,16)
         BOX 600,J+9,800,J+18,RGB(72,16,16),RGB(0,0,36),RGB(72,16,16),RGB(0,0,36)
         J = 638 + SPLITSET * 20
         BOX 599,J,801,J+19,RGB(120,16,16),RGB(120,16,16),RGB(120,16,16),RGB(120,16,16)
         BOX 600,J+1,800,J+9,RGB(0,0,36),RGB(72,16,16),RGB(0,0,36),RGB(72,16,16)
         BOX 600,J+9,800,J+18,RGB(72,16,16),RGB(0,0,36),RGB(72,16,16),RGB(0,0,36)
         J = 478 + LASTPLAYER * 20
         IF J < 498 THEN J = 498
         BOX 839,J,961,J+19,RGB(120,16,16),RGB(120,16,16),RGB(120,16,16),RGB(120,16,16)
         BOX 840,J+1,960,J+9,RGB(0,0,36),RGB(72,16,16),RGB(0,0,36),RGB(72,16,16)
         BOX 840,J+9,960,J+18,RGB(72,16,16),RGB(0,0,36),RGB(72,16,16),RGB(0,0,36)
         IF HOVERING=0
            IF WATCHFORNOHOVER=1
               WATCHFORNOHOVER=0
               RESET_TITLE=1
            ENDIF
         ENDIF
         INK RGB(240,160,40),RGB(0,0,0)         
         CENTER TEXT 50,680,"SCREEN MODE"
         // CENTER TEXT 200,320,"CARD BACK IMAGE"
         CENTER TEXT 200,500,"48 CARD DECKS"
         CENTER TEXT 200,520,"52 CARD DECKS"
         // CENTER TEXT 200,540,"56 CARD DECKS"
   
   
         CENTER TEXT 200,640,"FOUR DECKS" 
         CENTER TEXT 200,660,"SIX DECKS" 
         CENTER TEXT 200,680,"EIGHT DECKS"
   
   
         // CENTER TEXT 425,500,"ANY 777 PAYS 3 TO 1"
         J=540
         CENTER TEXT 425,J,"BONUS 777 PAYS 3 TO 1, SUIT 4 TO 1 "
         J=J+20
         CENTER TEXT 425,J,"BONUS 678 PAYS 3 TO 1, SUIT 4 TO 1 "
         // CENTER TEXT 425,520,"SUIT 777 PAYS 4 TO 1"
         // CENTER TEXT 425,540,"ANY 678 PAYS 3 TO 1" 
         // CENTER TEXT 425,560,"SUIT 678 PAYS 4 TO 1" 
         J=J+20
   
         CENTER TEXT 425,J,"DEALER 17 TIE WINS"
         J=J+20
         CENTER TEXT 425,J,"DEALER HITS SOFT 17"
         J=J+20
         CENTER TEXT 425,J,"UNBUSTED 5 CARD WIN"
         J=J+20
         CENTER TEXT 425,J,"SUIT BLACKJACK 2 TO 1"
         J=J+20
         CENTER TEXT 425,J,"SAME COLOR BLACKJACK 2 TO 1"
         J=J+20
         CENTER TEXT 425,J,"ALLOW PLAYER SURRENDER"         
         J=J+20
         CENTER TEXT 700,500,"DOUBLE DOWN ANY TOTAL"
         CENTER TEXT 700,520,"DOUBLE DOWN 10 OR 11"
         CENTER TEXT 700,540,"DOUBLE DOWN 9, 10, OR 11"
         CENTER TEXT 700,560,"DOUBLE DOWN UPTO 3 CARDS"
   
         CENTER TEXT 700,640,"SPLIT ANY PAIR"
         CENTER TEXT 700,660,"SPLIT EXACT PAIR"
         CENTER TEXT 700,680,"NO SPLIT ACES"                
   
         CENTER TEXT 900,500,"ONE PLAYER"
         CENTER TEXT 900,520,"TWO PLAYERS"
         CENTER TEXT 900,540,"THREE PLAYERS"         
   
         CENTER TEXT 900,660,"EXIT"
         CENTER TEXT 900,680,"BEGIN GAME"         
   
         IF SELECTED_RES_X > 1111
            CENTER TEXT 900,560,"FOUR PLAYERS"         
         ELSE
            INK RGB(120,80,20),RGB(0,0,0)
            CENTER TEXT 900,560,"FOUR PLAYERS"         
         ENDIF
      UNTIL SELECTING=2 OR SELECTING=3 OR RESET_TITLE=1
   UNTIL SELECTING=2 OR SELECTING=3
   REM GET IMAGE 255,0,0,640,480
   REM SAVE IMAGE "TITLE SCREEN SHOT.BMP",255
   CLS
   IF SELECTING = 3 THEN END_PROGRAM = TRUE
ENDROC